{{- if .Values.onvifVideo.enabled }}
apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: {{ .Values.onvifVideo.name }}
spec:
  protocol:
    onvif:
      ipAddresses: 
        action: {{ .Values.onvifVideo.ipAddresses.action }}
        {{- if .Values.onvifVideo.ipAddresses.items}}
        items:
        {{- toYaml .Values.onvifVideo.ipAddresses.items | nindent 8 }}
        {{- else }}
        items: []
        {{- end }}
      macAddresses:
        action: {{ .Values.onvifVideo.macAddresses.action }}
        {{- if .Values.onvifVideo.macAddresses.items}}
        items:
        {{- toYaml .Values.onvifVideo.macAddresses.items | nindent 8 }}
        {{- else }}
        items: []
        {{- end }}
      scopes:
        action: {{ .Values.onvifVideo.scopes.action }}
        {{- if .Values.onvifVideo.scopes.items}}
        items:
        {{- toYaml .Values.onvifVideo.scopes.items | nindent 8 }}
        {{- else }}
        items: []
        {{- end }}
      discoveryTimeoutSeconds: {{ .Values.onvifVideo.discoveryTimeoutSeconds }}
  brokerPodSpec:
    containers:
    - name: {{ .Values.onvifVideo.name }}-broker
      {{- if .Values.useDevelopmentContainers }}
      {{- if .Values.useLatestContainers }}
      image: {{ printf "%s:latest-dev" .Values.onvifVideo.brokerPod.image.repository | quote }}
      {{- else }}
      image: {{ printf "%s:%s" .Values.onvifVideo.brokerPod.image.repository (default (printf "v%s-dev" .Chart.AppVersion) .Values.onvifVideo.brokerPod.image.tag) | quote }}
      {{- end }}
      {{- else }}
      {{- if .Values.useLatestContainers }}
      image: {{ printf "%s:latest" .Values.onvifVideo.brokerPod.image.repository | quote }}
      {{- else }}
      image: {{ printf "%s:%s" .Values.onvifVideo.brokerPod.image.repository (default (printf "v%s" .Chart.AppVersion) .Values.onvifVideo.brokerPod.image.tag) | quote }}
      {{- end }}
      {{- end }}
      imagePullPolicy: {{ .Values.onvifVideo.brokerPod.image.pullPolicy }}
      resources:
        limits:
          {{`"{{PLACEHOLDER}}"`}} : "1"
    {{- with .Values.imagePullSecrets }}
    imagePullSecrets:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  instanceServiceSpec:
    type: {{ .Values.onvifVideo.instanceService.type }}
    ports:
    - name: grpc
      port: {{ .Values.onvifVideo.instanceService.port }}
      protocol: {{ .Values.onvifVideo.instanceService.protocol }}
      targetPort: {{ .Values.onvifVideo.instanceService.targetPort }}
  configurationServiceSpec:
    type: {{ .Values.onvifVideo.configurationService.type }}
    ports:
    - name: grpc
      port: {{ .Values.onvifVideo.configurationService.port }}
      protocol: {{ .Values.onvifVideo.configurationService.protocol }}
      targetPort: {{ .Values.onvifVideo.configurationService.targetPort }}
  {{- if .Values.onvifVideo.properties }}
  properties:
  {{- toYaml . | nindent 4 }}
  {{- else }}
  properties: {}
  {{- end }}
  capacity: {{ .Values.onvifVideo.capacity }}
{{- end }}