{{- if .Values.udevVideo.enabled }}
apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: {{ .Values.udevVideo.name }}
spec:
  protocol:
    udev:
      udevRules:
      {{- toYaml .Values.udevVideo.udevRules | nindent 6 }}
  brokerPodSpec:
    containers:
    - name: {{ .Values.udevVideo.name }}-broker
      {{- if .Values.useDevelopmentContainers }}
      {{- if .Values.useLatestContainers }}
      image: {{ printf "%s:latest-dev" .Values.udevVideo.brokerPod.image.repository | quote }}
      {{- else }}
      image: {{ printf "%s:%s" .Values.udevVideo.brokerPod.image.repository (default (printf "v%s-dev" .Chart.AppVersion) .Values.udevVideo.brokerPod.image.tag) | quote }}
      {{- end }}
      {{- else }}
      {{- if .Values.useLatestContainers }}
      image: {{ printf "%s:latest" .Values.udevVideo.brokerPod.image.repository | quote }}
      {{- else }}
      image: {{ printf "%s:%s" .Values.udevVideo.brokerPod.image.repository (default (printf "v%s" .Chart.AppVersion) .Values.udevVideo.brokerPod.image.tag) | quote }}
      {{- end }}
      {{- end }}
      imagePullPolicy: {{ .Values.udevVideo.brokerPod.image.pullPolicy }}
      env: 
        - name: FORMAT 
          value: {{ quote .Values.udevVideo.brokerPod.env.format }} 
        - name: RESOLUTION_WIDTH 
          value: {{ quote .Values.udevVideo.brokerPod.env.width }} 
        - name: RESOLUTION_HEIGHT
          value: {{ quote .Values.udevVideo.brokerPod.env.height }}
        - name: FRAMES_PER_SECOND
          value: {{ quote .Values.udevVideo.brokerPod.env.fps }}
      securityContext:
        privileged: true
      resources:
        limits:
          {{`"{{PLACEHOLDER}}"`}} : "1"
    {{- with .Values.imagePullSecrets }}
    imagePullSecrets:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  instanceServiceSpec:
    type: {{ .Values.udevVideo.instanceService.type }}
    ports:
    - name: grpc
      port: {{ .Values.udevVideo.instanceService.port }}
      protocol: {{ .Values.udevVideo.instanceService.protocol }}
      targetPort: {{ .Values.udevVideo.instanceService.targetPort }}
  configurationServiceSpec:
    type: {{ .Values.udevVideo.configurationService.type }}
    ports:
    - name: grpc
      port: {{ .Values.udevVideo.configurationService.port }}
      protocol: {{ .Values.udevVideo.configurationService.protocol }}
      targetPort: {{ .Values.udevVideo.configurationService.targetPort }}
  {{- if .Values.udevVideo.properties }}
  properties:
  {{- toYaml . | nindent 4 }}
  {{- else }}
  properties: {}
  capacity: {{ .Values.udevVideo.capacity }}
  {{- end }}
{{- end }}