apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  apiServerAddress: "0.0.0.0"
  disableDefaultCNI: true
  
kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  metadata:
    name: config
  etcd:
    local:
      extraArgs:
        "listen-metrics-urls": "http://0.0.0.0:2378"
  apiServer:
    extraArgs:
      "enable-admission-plugins": "NamespaceLifecycle,LimitRanger,PodNodeSelector,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota"

nodes:
- role: control-plane
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 31080
    hostPort: 31080
    # Istio HTTP2
  - containerPort: 31380
    hostPort: 31380
    # Istio HTTPS
  - containerPort: 31390
    hostPort: 31390
    # Istio TCP
  - containerPort: 31400
    hostPort: 31400
  - containerPort: 80
    hostPort: 80
  - containerPort: 443
    hostPort: 443
