apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: localstack
  name: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: localstack
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: localstack
    spec:
      containers:
      - env:
        - name: DATA_DIR
          value: ' '
        - name: DEBUG
          value: ' '
        - name: DOCKER_HOST
          value: unix:///var/run/docker.sock
        - name: HOST_TMP_FOLDER
        - name: KINESIS_ERROR_PROBABILITY
          value: ' '
        - name: LAMBDA_EXECUTOR
          value: ' '
        - name: PORT_WEB_UI
          value: ' '
        - name: SERVICES
          value: ' '
        image: localstack/localstack
        imagePullPolicy: ""
        name: localstack-main
        ports:
        - containerPort: 4566
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /tmp/localstack
          name: localstack-claim0
        - mountPath: /var/run/docker.sock
          name: localstack-claim1
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: localstack-claim0
        persistentVolumeClaim:
          claimName: localstack-claim0
      - name: localstack-claim1
        persistentVolumeClaim:
          claimName: localstack-claim1
status: {}
