apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: localstack
  name: localstack
spec:
  ports:
  - name: "4566"
    port: 4566
    targetPort: 4566
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: localstack
status:
  loadBalancer: {}
