{{- $annotations := .Values.annotations -}}
{{- $labels := .Values.labels -}}
{{- $helmResourcePolicy := .Values.helmResourcePolicy -}}
{{- range $key := .Values.namespaces -}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ . }}
  labels:
    {{- include "namespace.labels" $ | nindent 4 }}
{{- with $labels }}
    {{ toYaml . | nindent 4 }}
{{- end }}
{{- with $annotations }}
  annotations:
    helm.sh/resource-policy: "{{ $helmResourcePolicy }}"
{{ toYaml . | indent 4 }}
{{- end }}
    
{{- end -}}