---
bases:
- ../config/environments.yaml
- ../config/helmdefaults.yaml
---

repositories:
- name: reactiveops-stable
  url: https://charts.reactiveops.com/stable

releases:
- name: namespace-security
  chart: ../charts/namespace/chart/namespace
  namespace: kube-system
  labels:
    chart: namespace-security
    component: security
    namespace: kube-system
  wait: true
  installed: true
  values:
  - namespaces:
    - {{ .Values.stacks.security.namespace | default "security" }}
    helmResourcePolicy: keep
    annotations:
      certmanager.k8s.io/disable-validation: "true"
      {{ .Values.cloud | default "local" }}-key-vault-env-injection: enabled

- name: rbac-manager
  namespace: {{ .Values.stacks.security.namespace | default "security" }}
  labels:
    chart: "rbac-manager"
    repo: "stable"
    component: "security"
    namespace: "security"
    vendor: "reactiveops"
    default: "false"
    certmanager.k8s.io/disable-validation: "true"
  version: "1.4.1"
  installed: true
  chart: reactiveops-stable/rbac-manager
  needs:
  - kube-system/namespace-security

- name: config-security
  namespace: {{ .Values.stacks.security.namespace | default "security" }}
  chart: {{ .Values.archtypeChart | default "../charts/archtype" }}
  labels:
    chart: config-security
    component: security
    namespace: {{ .Values.stacks.security.namespace | default "security" }}
    {{ .Values.cloud | default "local" }}-key-vault-env-injection: enabled
  needs:
  - security/rbac-manager
  values:
  - project:
      team: platform
      target: {{ .Values.cloud | default "local" }}
      client: mcd
      workload: rbac
      app: security
    clusterRole:
      enabled: true
      name: security-namespace-cluster-admin
    clusterRoleBinding:
      enabled: true
      roleName: security-namespace-cluster-admin
      serviceAccountNamespace: {{ .Values.stacks.security.namespace | default "security" }}
      serviceAccountName: default

- name: security-roles
  chart: incubator/raw
  namespace: kube-system
  needs:
  - security/rbac-manager
  values:
  - resources:
    - kind: ServiceAccount
      apiVersion: v1
      metadata:
        name: platform-admin
        namespace: kube-system
    - kind: ClusterRoleBinding
      apiVersion: rbac.authorization.k8s.io/v1beta1
      metadata:
        name: platform-admin
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
      - kind: ServiceAccount
        name: platform-admin
        namespace: kube-system
    - kind: ClusterRoleBinding
      apiVersion: rbac.authorization.k8s.io/v1beta1
      metadata:
        name: kubernetes-dashboard
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
      - kind: ServiceAccount
        name: kubernetes-dashboard
        namespace: kube-system
    - kind: ClusterRoleBinding
      apiVersion: rbac.authorization.k8s.io/v1beta1
      metadata:
        name: kubernetes-platform-admin
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
      - kind: ServiceAccount
        name: default
        namespace: platform
