---
bases:
- ../config/environments.yaml
- ../config/helmdefaults.yaml
- ../config/repositories.yaml
---

## Gitlab
# Values - https://docs.gitlab.com/charts/charts/globals.html
releases:
- name: gitlab-namespace
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.8" }}
  namespace: kube-system
  condition: gitlab.enabled
  installed: true
  wait: true
  labels:
    chart: gitlab-namespace
    component: gitlab
    namespace: kube-system
  values:
  - app: gitlab-namespace
    namespace:
      enabled: true
      name: {{ .Values | getOrNil "gitlab.namespace" | default "gitlab" }}

- name: gitlab
  chart: {{ .Values | getOrNil "gitlab.chart" | default "gitlab/gitlab" }}
  version: {{ .Values | getOrNil "gitlab.version" | default "4.2.2" }}
  namespace: {{ .Values | getOrNil "gitlab.namespace" | default "gitlab" }}
  condition: gitlab.enabled
  installed: true
  timeout: 1200
  missingFileHandler: Debug
  labels:
    chart: gitlab
    component: gitlab
    namespace: {{ .Values | getOrNil "gitlab.namespace" | default "gitlab" }}
  needs:
    - kube-system/gitlab-namespace
  values:
  - global:
      gitlabVersion: {{ .Values | getOrNil "gitlab.gitlabVersion" | default "13.2.2" }}
      grafana:
        enabled: false
      ingress:
        enabled: false
        configureCertmanager: false
        tls:
          enabled: false
      hosts:
        https: false
        domain: {{ .Values | getOrNil "ingress.internal.zone" | default "int" }}.{{ .Values | getOrNil "dnsRoot" | default "micro.svc" }}
        gitlab:
          name: gitlab.{{ .Values | getOrNil "dnsRoot" | default "micro.svc" }}
          https: false
          serviceName: webservice
        registry:
          name: registry.{{ .Values | getOrNil "ingress.internal.zone" | default "int" }}.{{ .Values | getOrNil "dnsRoot" | default "micro.svc" }}
          https: false
          serviceName: registry
        minio:
          name: minio.{{ .Values | getOrNil "ingress.internal.zone" | default "int" }}.{{ .Values | getOrNil "dnsRoot" | default "micro.svc" }}
          https: false
          serviceName: minio
    minio:
      persistence:
        size: 2Gi
    certmanager:
      install: false
    nginx-ingress:
      enabled: false
    prometheus:
      install: false
    gitlab-runner:
      install: false
    
  - "../config/{{ .Environment.Name }}/gitlab.override.yaml"

- name: gitlab-ingress
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.8" }}
  namespace: {{ .Values | getOrNil "gitlab.namespace" | default "gitlab" }}
  condition: ingress.enabled
  installed: true
  needs:
  - kube-system/gitlab-namespace
  - {{ .Values | getOrNil "gitlab.namespace" | default "gitlab" }}/gitlab
  labels:
    chart: gitlab-ingress
    component: ingress
    namespace: {{ .Values | getOrNil "gitlab.namespace" | default "gitlab" }}
  values:
  - app: gitlab
    dnsRoot: {{ .Values | getOrNil "dnsRoot" | default "micro.svc" }}
    zone: {{ .Values | getOrNil "homeassistant.zone" | default "internal" }}
    ingressClassMap:
      internal: {{ .Values | getOrNil "ingress.internal.class" | default "internal" }}
    ingress:
      enabled: true
      tlsEnabled: true
      hosts:
      - secretName: gitlab-ingress
        paths:
        - path: "/"
          backend:
            serviceName: gitlab-webservice
            servicePort: 8080
