---
bases:
- ../config/environments.yaml
- ../config/helmdefaults.yaml
- ../config/repositories.yaml
---

releases:
- name: nfsstorage-namespace
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.2" }}
  namespace: kube-system
  condition: nfsstorage.enabled
  installed: true
  wait: true
  labels:
    chart: nfsstorage-namespace
    component: nfsstorage
    namespace: kube-system
  values:
  - app: nfsstorage
    namespace:
      enabled: true
      name: {{ .Values | getOrNil "nfsstorage.namespace" | default "nfsstorage" }}

- name: nfsstorage
  chart: {{ .Values | getOrNil "nfsstorage.chart" | default "stable/nfs-client-provisioner" }}
  version: {{ .Values | getOrNil "nfsstorage.version" | default "1.2.8" }}
  namespace: {{ .Values | getOrNil "nfsstorage.namespace" | default "nfsstorage" }}
  condition: nfsstorage.enabled
  installed: true
  missingFileHandler: Debug
  labels:
    chart: nfsstorage
    component: nfsstorage
    namespace: {{ .Values | getOrNil "nfsstorage.namespace" | default "nfsstorage" }}
  needs:
    - kube-system/nfsstorage-namespace
  values:
  - storageClass:
      create: true
      defaultClass: {{ .Values | getOrNil "nfsstorage.defaultClass" | default "true" }}
    nfs:
      server: {{ .Values | getOrNil "nfsstorage.server" | default "127.0.0.1" }}
      path: {{ .Values | getOrNil "nfsstorage.path" | default "/mnt/nfs/kube" }}
      mountOptions:
  - "../config/{{ .Environment.Name }}/nfsstorage.override.yaml"