---
bases:
- ../config/environments.yaml
- ../config/{{ .Environment.Name }}/helmdefaults.yaml
- ../config/{{ .Environment.Name }}/repositories.yaml
---

releases:
- name: namespace-{{ .Values.consul.name }}
  chart: {{ .Values.archetype.chart }}
  version: {{ .Values.archetype.version }}
  namespace: kube-system
  condition: consul.enabled
  installed: true
  wait: true
  labels:
    chart: namespace-{{ .Values.consul.name }}
    component: {{ .Values.consul.name }}
    namespace: kube-system
  values:
  - app: {{ .Values.consul.name }}
    namespace:
      enabled: true
      name: {{ .Values.consul.namespace }}

## consul Deployment
- name: {{ .Values.consul.name }}
  chart: {{ .Values.consul.chart }}
  version: {{ .Values.consul.version }}
  namespace: {{ .Values.consul.namespace }}
  condition: consul.enabled
  installed: true
  labels:
    chart: {{ .Values.consul.name }}
    component: {{ .Values.consul.name }}
    namespace: {{ .Values.consul.namespace }}
  needs:
    - kube-system/namespace-{{ .Values.consul.name }}
  values:
  - dns:
      enabled: false
    client:
      enabled: true
    server:
      replicas: 1
      bootstrapExpect: 1
      disruptionBudget:
        maxUnavailable: 0
      storage: 2Gi
    ui:
      enabled: true
    service:
      type: LoadBalancer
    consulNamespaces:
      consulDestinationNamespace: kube
      mirroringK8S: false

- name: ingress-{{ .Values.consul.name }}
  namespace: {{ .Values.consul.namespace }}
  chart: {{ .Values.archetype.chart }}
  version: {{ .Values.archetype.version }}
  condition: consul.enabled
  installed: true
  needs:
  - kube-system/namespace-{{ .Values.consul.name }}
  labels:
    chart: ingress-{{ .Values.consul.name }}
    component: ingress
    namespace: {{ .Values.consul.namespace }}
  values:
  - zone: internal
    app: consul-dashboard
    ingressClassMap:
      internal: {{ .Values.ingress.internal.class }}
    ingress:
      enabled: true
      tlsEnabled: true
      hosts:
      - name: consul.{{ .Values.ingress.internal.zone }}
        secretName: ingress-consul-dashboard
        config:
          http:
            paths:
            - path: "/"
              backend:
                serviceName: consul-consul-ui
                servicePort: 80
