---
bases:
- ../config/environments.yaml
- ../config/{{ .Environment.Name }}/helmdefaults.yaml
- ../config/{{ .Environment.Name }}/repositories.yaml
---

releases:
- name: namespace-security
  chart: {{ .Values.archetype.chart }}
  version: {{ .Values.archetype.version }}
  namespace: kube-system
  installed: true
  wait: true
  labels:
    chart: namespace-security
    component: security
    namespace: kube-system
  values:
  - app: security
    namespace:
      enabled: true
      name: {{ .Values.security.namespace }}
      annotations:
        certmanager.k8s.io/disable-validation: "true"
#        {{ .Values.cloud }}-key-vault-env-injection: enabled

- name: rbac-manager
  chart: {{ .Values.rbacmanager.chart }}
  namespace: {{ .Values.security.namespace }}
  version: {{ .Values.rbacmanager.version }}
  condition: rbacmanager.enabled
  installed: true
  labels:
    chart: rbac-manager
    component: security
    namespace: {{ .Values.security.namespace }}
  needs:
  - kube-system/namespace-security

- name: config-security
  namespace: {{ .Values.security.namespace }}
  chart: {{ .Values.archetype.chart }}
  version: {{ .Values.archetype.version }}
  installed: true
  labels:
    chart: config-security
    component: security
    namespace: {{ .Values.security.namespace }}
  needs:
  - {{ .Values.security.namespace }}/rbac-manager
  values:
  - app: config-security
    clusterRole:
      enabled: true
      name: security-namespace-cluster-admin
    clusterRoleBinding:
      enabled: true
      roleName: security-namespace-cluster-admin
      serviceAccountNamespace: {{ .Values.security.namespace }}
      serviceAccountName: default
