---
bases:
- ../config/environments.yaml
- ../config/helmdefaults.yaml
- ../config/repositories.yaml
---

###############
## Rancher Deployment
releases:
- name: rancher-namespace
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.8" }}
  namespace: kube-system
  wait: true
  installed: true
  labels:
    chart: rancher-namespace
    component: rancher
    namespace: kube-system
  values:
  - app: rancher
    namespace:
      enabled: true
      name: {{ .Values | getOrNil "rancher.namespace" | default "cattle-system" }}

## rancher Deployment
- name: rancher
  namespace: {{ .Values | getOrNil "rancher.namespace" | default "cattle-system" }}
  chart: {{ .Values | getOrNil "rancher.chart" | default "rancher/rancher" }}
  installed: true
  missingFileHandler: Debug
  labels:
    chart: rancher
    component: rancher
    namespace: {{ .Values | getOrNil "rancher.namespace" | default "cattle-system" }}
  needs:
    - kube-system/rancher-namespace
  values:
  - hostname: rancher.{{ .Values | getOrNil "ingress.internal.zone" | default "int.micro.svc" }}
  - "../config/{{ .Environment.Name }}/rancher.override.yaml"


