---
bases:
- ../config/environments.yaml
- ../config/helmdefaults.yaml
---

repositories:
- name: incubator
  url: https://kubernetes-charts-incubator.storage.googleapis.com

releases:
- name: bookinfo-ingress
  chart: incubator/raw
  install: true
  namespace: default
  values:
  - resources:
    - kind: Ingress
      apiVersion: extensions/v1beta1
      metadata:
        name: bookinfo
      spec:
        rules:
        - host: bookinfo.{{ .Values.stacks.ingress.zoneInternal }}
          http:
            paths:
            - path: /productpage
              backend:
                serviceName: productpage
                servicePort: 9080
            - path: /login
              backend:
                serviceName: productpage
                servicePort: 9080
            - path: /logout
              backend:
                serviceName: productpage
                servicePort: 9080
            - path: /static/*
              backend:
                serviceName: productpage
                servicePort: 9080

# - name: bookinfo-disable-mutual-tls
#   chart: incubator/raw
#   namespace: default
#   install: true
#   values:
#   - resources:
#     - apiVersion: "authentication.istio.io/v1alpha1"
#       kind: Policy
#       metadata:
#         name: default
#       spec:
#         peers: []
#     - apiVersion: networking.istio.io/v1alpha3
#       kind: DestinationRule
#       metadata:
#         name: productpage
#       spec:
#         host: productpage
#         subsets:
#         - name: v1
#           labels:
#             version: v1
#     - apiVersion: networking.istio.io/v1alpha3
#       kind: DestinationRule
#       metadata:
#         name: reviews
#       spec:
#         host: reviews
#         subsets:
#         - name: v1
#           labels:
#             version: v1
#         - name: v2
#           labels:
#             version: v2
#         - name: v3
#           labels:
#             version: v3
#     - apiVersion: networking.istio.io/v1alpha3
#       kind: DestinationRule
#       metadata:
#         name: ratings
#       spec:
#         host: ratings
#         subsets:
#         - name: v1
#           labels:
#             version: v1
#         - name: v2
#           labels:
#             version: v2
#         - name: v2-mysql
#           labels:
#             version: v2-mysql
#         - name: v2-mysql-vm
#           labels:
#             version: v2-mysql-vm
#     - apiVersion: networking.istio.io/v1alpha3
#       kind: DestinationRule
#       metadata:
#         name: details
#       spec:
#         host: details
#         subsets:
#         - name: v1
#           labels:
#             version: v1
#         - name: v2
#           labels:
#             version: v2
