---
bases:
- ../config/environments.yaml
- ../config/helmdefaults.yaml
- ../config/repositories.yaml
---

## Prometheus Operator
# site: https://github.com/helm/charts/blob/master/stable/prometheus-operator/values.yaml
releases:
- name: po-namespace
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.2" }}
  namespace: kube-system
  condition: prometheusoperator.enabled
  installed: true
  wait: true
  labels:
    chart: po-namespace
    component: po
    namespace: kube-system
  values:
  - app: po
    namespace:
      enabled: true
      name: {{ .Values | getOrNil "prometheusoperator.namespace" | default "prometheus-operator" }}

- name: po
  chart: {{ .Values | getOrNil "prometheusoperator.chart" | default "stable/prometheus-operator" }}
  version: {{ .Values | getOrNil "prometheusoperator.version" | default "8.13.8" }}
  namespace: {{ .Values | getOrNil "prometheusoperator.namespace" | default "prometheus-operator" }}
  condition: prometheusoperator.enabled
  installed: true
  missingFileHandler: Debug
  labels:
    chart: po
    component: po
    namespace: {{ .Values | getOrNil "prometheusoperator.namespace" | default "prometheus-operator" }}
  needs:
  - kube-system/po-namespace
  values:
  - fullnameOverride: po
    alertmanager:
      alertmanagerSpec:
        externalUrl: http://alertmanager.{{ .Values | getOrNil "ingress.internal.zone" | default "int" }}.{{ .Values | getOrNil "dnsRoot" | default "micro.svc" }}
    prometheus:
      prometheusSpec:
        externalUrl: http://prometheus.{{ .Values | getOrNil "ingress.internal.zone" | default "int" }}.{{ .Values | getOrNil "dnsRoot" | default "micro.svc" }}
  - "../config/{{ .Environment.Name }}/po.override.yaml"

- name: po-grafana-ingress
  namespace: {{ .Values | getOrNil "prometheusoperator.namespace" | default "prometheus-operator" }}
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.2" }}
  condition: ingress.enabled
  installed: true
  needs:
  - kube-system/po-namespace
  - {{ .Values | getOrNil "prometheusoperator.namespace" | default "prometheus-operator" }}/po
  labels:
    chart: po-grafana-ingress
    component: po
    namespace: {{ .Values | getOrNil "prometheusoperator.namespace" | default "prometheus-operator" }}
  values:
  - app: grafana
    dnsRoot: {{ .Values | getOrNil "dnsRoot" | default "micro.svc" }}
    zone: {{ .Values | getOrNil "prometheusoperator.zone" | default "internal" }}
    ingressClassMap:
      internal: {{ .Values | getOrNil "ingress.internal.class" | default "internal" }}
      external: {{ .Values | getOrNil "ingress.external.class" | default "external" }}
      stage: {{ .Values | getOrNil "ingress.stage.class" | default "stage" }}
    zoneMap:
      internal: {{ .Values | getOrNil "ingress.internal.zone" | default "int" }}
      external: {{ .Values | getOrNil "ingress.external.zone" | default "ext" }}
      staging: {{ .Values | getOrNil "ingress.stage.zone" | default "stage" }}
      default: ""
    ingress:
      enabled: true
      tlsEnabled: true
      hosts:
      - secretName: po-grafana-ingress
        config:
          http:
            paths:
            - path: "/"
              backend:
                serviceName: po-grafana
                servicePort: 80

- name: po-prometheus-ingress
  namespace: {{ .Values | getOrNil "prometheusoperator.namespace" | default "prometheus-operator" }}
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.2" }}
  condition: ingress.enabled
  installed: true
  needs:
  - kube-system/po-namespace
  - {{ .Values | getOrNil "prometheusoperator.namespace" | default "prometheus-operator" }}/po
  labels:
    chart: po-prometheus-ingress
    component: po
    namespace: {{ .Values | getOrNil "prometheusoperator.namespace" | default "prometheus-operator" }}
  values:
  - app: prometheus
    dnsRoot: {{ .Values | getOrNil "dnsRoot" | default "micro.svc" }}
    zone: {{ .Values | getOrNil "prometheusoperator.zone" | default "internal" }}
    ingressClassMap:
      internal: {{ .Values | getOrNil "ingress.internal.class" | default "internal" }}
      external: {{ .Values | getOrNil "ingress.external.class" | default "external" }}
      stage: {{ .Values | getOrNil "ingress.stage.class" | default "stage" }}
    zoneMap:
      internal: {{ .Values | getOrNil "ingress.internal.zone" | default "int" }}
      external: {{ .Values | getOrNil "ingress.external.zone" | default "ext" }}
      staging: {{ .Values | getOrNil "ingress.stage.zone" | default "stage" }}
      default: ""
    ingress:
      enabled: true
      tlsEnabled: true
      hosts:
      - secretName: po-prometheus-ingress
        config:
          http:
            paths:
            - path: "/"
              backend:
                serviceName: po-prometheus
                servicePort: 9090

- name: po-alertmanager-ingress
  namespace: {{ .Values | getOrNil "prometheusoperator.namespace" | default "prometheus-operator" }}
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.2" }}
  condition: ingress.enabled
  installed: true
  needs:
  - kube-system/po-namespace
  - {{ .Values | getOrNil "prometheusoperator.namespace" | default "prometheus-operator" }}/po
  labels:
    chart: po-alertmanager-ingress
    component: po
    namespace: {{ .Values | getOrNil "prometheusoperator.namespace" | default "prometheus-operator" }}
  values:
  - app: alertmanager
    dnsRoot: {{ .Values | getOrNil "dnsRoot" | default "micro.svc" }}
    zone: {{ .Values | getOrNil "prometheusoperator.zone" | default "internal" }}
    ingressClassMap:
      internal: {{ .Values | getOrNil "ingress.internal.class" | default "internal" }}
      external: {{ .Values | getOrNil "ingress.external.class" | default "external" }}
      stage: {{ .Values | getOrNil "ingress.stage.class" | default "stage" }}
    zoneMap:
      internal: {{ .Values | getOrNil "ingress.internal.zone" | default "int" }}
      external: {{ .Values | getOrNil "ingress.external.zone" | default "ext" }}
      staging: {{ .Values | getOrNil "ingress.stage.zone" | default "stage" }}
      default: ""
    ingress:
      enabled: true
      tlsEnabled: true
      hosts:
      - secretName: po-alertmanager-ingress
        config:
          http:
            paths:
            - path: "/"
              backend:
                serviceName: po-alertmanager
                servicePort: 9093