---
bases:
- ../config/environments.yaml
- ../config/{{ .Environment.Name }}/helmdefaults.yaml
- ../config/{{ .Environment.Name }}/repositories.yaml
---

## Traefik
# Dashboard - http://traefik.int.micro.svc/dashboard/#/

releases:
- name: {{ .Values.traefik.name }}-namespace
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.1" }}
  namespace: kube-system
  wait: true
  condition: ingress.enabled
  installed: true
  labels:
    chart: {{ .Values.traefik.name }}-namespace
    component: ingress
    namespace: kube-system
  values:
  - app: traefik
    namespace:
      enabled: true
      name: {{ .Values.ingress.internal.namespace }}

## traefik Deployment
- name: {{ .Values.traefik.name }}
  chart: {{ .Values.traefik.chart }}
  version: {{ .Values.traefik.version }}
  namespace: {{ .Values.ingress.internal.namespace }}
  condition: ingress.enabled
  installed: true
  labels:
    chart: traefik
    component: traefik
    namespace: {{ .Values.ingress.internal.namespace }}
  needs:
  - kube-system/{{ .Values.traefik.name }}-namespace
  values:
  - globalArguments:
    - "--global.checknewversion=false"
    - "--global.sendanonymoususage=false"
    - "--api.insecure=true"
    additionalArguments:
      - "--providers.kubernetesingress=true"
      - "--providers.kubernetesingress.ingressclass={{ .Values | getOrNil "ingress.internal.class" | default "internal" }}"
    ingressRoute:
      dashboard:
        enabled: false
        annotations:
          "cert-manager.io/cluster-issuer": "default"
          "kubernetes.io/ingress.class": "internal"
          "service.beta.kubernetes.io/local-load-balancer-internal": "true"
    service:
      type: LoadBalancer
      spec:
        externalTrafficPolicy: Cluster
        {{- if (ne .Values.ingress.internal.ip "") | default "" }}
        loadBalancerIP: "{{ .Values.ingress.internal.ip }}"
        {{- end }}
      annotations:
        "prometheus.io/scrape": "{{ .Values.prometheusoperator.enabled }}"
        "prometheus.io/port": "9913"
        "service.beta.kubernetes.io/{{ .Values.cloud }}-load-balancer-internal": "true"
    ports:
      traefik:
        expose: true

- name: {{ .Values.traefik.name }}-dashboard
  chart: {{ .Values | getOrNil "raw.chart" | default "incubator/raw" }}
  version: {{ .Values | getOrNil "raw.version" | default "0.2.3" }}
  namespace: {{ .Values.ingress.internal.namespace }}
  condition: traefik.enabled
  installed: true
  labels:
    chart: traefik-dashboard
    component: ingress
    namespace: {{ .Values.ingress.internal.namespace }}
  needs:
  - "{{ .Values.ingress.internal.namespace }}/{{ .Values.traefik.name }}"
  values:
  - resources:
    - apiVersion: traefik.containo.us/v1alpha1
      kind: IngressRoute
      metadata:
        name: {{ .Values.traefik.name }}-dashboard
      spec:
        entryPoints:
          - web
        routes:
          - match: Host(`traefik.{{ .Values | getOrNil "ingress.internal.zone" | default "int.micro.svc" }}`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
            kind: Rule
            services:
              - name: api@internal
                kind: TraefikService
