---
bases:
- ../config/environments.yaml
- ../config/helmdefaults.yaml
---

repositories:
- name: rancher
  url: https://releases.rancher.com/server-charts/latest

###############
## Rancher Deployment
releases:
- name: namespace-rancher
  chart: {{ .Values.archetypeChart }}
  namespace: kube-system
  labels:
    chart: namespace-rancher
    component: rancher
    namespace: kube-system
  wait: true
  installed: true
  values:
  - app: rancher
    namespace:
      enabled: true
      name: cattle-system

## rancher Deployment
- name: rancher
  namespace: cattle-system
  installed: true
  chart: rancher/rancher
  labels:
    chart: rancher
    component: rancher
    namespace: cattle-system
  needs:
    - kube-system/namespace-rancher
  values:
  - hostname: rancher.{{ .Values.stacks.ingress.zoneInternal }}
    ingress:
      extraAnnotations:
        kubernetes.io/ingress.class: {{ .Values.stacks.ingress.classInternal }}
#        certmanager.k8s.io/cluster-issuer: {{ .Values.stacks.certmanager.issuerDefault }}

# - name: ingress-rancher
#   namespace: cattle-system
#   chart: {{ .Values.archetypeChart }}
#   installed: true
#   needs:
#   - kube-system/namespace-rancher
#   labels:
#     chart: ingress-rancher
#     component: ingress
#     namespace: cattle-system
#   values:
#   - zone: internal
#     app: rancher-dashboard
#     ingressClassMap:
#       internal: {{ .Values.stacks.ingress.classInternal }}
#     ingress:
#       enabled: true
#       tlsEnabled: true
#       hosts:
#       - name: rancher.{{ .Values.stacks.ingress.zoneInternal }}
#         secretName: ingress-rancher-dashboard
#         config:
#           http:
#             paths:
#             - path: "/"
#               backend:
#                 serviceName: rancher
#                 servicePort: 9092
