---
bases:
- ../config/environments.yaml
- ../config/helmdefaults.yaml
---

repositories:
- name: incubator
  url: https://kubernetes-charts-incubator.storage.googleapis.com
- name: traefik
  url: "git+https://github.com/containous/traefik-helm-chart@/traefik"

###############
## traefik
releases:
- name: namespace-traefik
  chart: {{ .Values.archetypeChart }}
  namespace: kube-system
  labels:
    chart: namespace-traefik
    component: ingress
    namespace: kube-system
  wait: true
  installed: true
  values:
  - app: traefik
    namespace:
      enabled: true
      name: {{ .Values.stacks.ingress.namespaceInternal }}

## traefik Deployment
- name: traefik
  namespace: {{ .Values.stacks.ingress.namespaceInternal }}
  installed: true
  chart: traefik/traefik
  labels:
    chart: traefik
    component: traefik
    namespace: "{{ .Values.stacks.ingress.namespaceInternal }}"
  needs:
    - kube-system/namespace-traefik
  values:
  - globalArguments:
    - "--global.checknewversion=false"
    - "--global.sendanonymoususage=false"
    additionalArguments:
      - "--providers.kubernetesingress=true"
      - "--providers.kubernetesingress.ingressclass={{ .Values.stacks.ingress.classInternal }}"
    ingressRoute:
      dashboard:
        enabled: false
    service:
      type: LoadBalancer
      spec:
        externalTrafficPolicy: Cluster
        {{- if .Values.stacks.ingress.ipInternal | default "" }}
        loadBalancerIP: "{{ .Values.stacks.ingress.ipInternal | default "" }}"
        {{- end }}
      annotations:
        "prometheus.io/scrape": "true"
        "prometheus.io/port": "9913"
        "service.beta.kubernetes.io/{{ .Values.cloud }}-load-balancer-internal": "true"
    ports:
      traefik:
        expose: true

- name: ingress-traefik
  namespace: "{{ .Values.stacks.ingress.namespaceInternal }}"
  chart: {{ .Values.archetypeChart }}
  installed: true
  needs:
  - kube-system/namespace-traefik
  labels:
    chart: ingress-dashboard
    component: ingress
    namespace: "{{ .Values.stacks.ingress.namespaceInternal }}"
  values:
  - zone: internal
    app: traefik-dashboard
    ingressClassMap:
      internal: {{ .Values.stacks.ingress.classInternal }}
    # certificate:
    #   enabled: true
    #   name: dashboard-ingress-cert
    #   selfSigned: true
    #   commonName: dashboard.{{ .Values.stacks.ingress.zoneInternal }}
    #   isCA: false
    ingress:
      enabled: true
      tlsEnabled: true
      hosts:
      - name: traefik.{{ .Values.stacks.ingress.zoneInternal }}
        secretName: ingress-traefik-dashboard
        config:
          http:
            paths:
            - path: "/dashboard"
              backend:
                serviceName: traefik
                servicePort: 443

# - name: traefik-dashboard
#   namespace: {{ .Values.stacks.ingress.namespaceInternal }}
#   chart: incubator/raw
#   installed: true
#   labels:
#     chart: traefik-dashboard
#     component: ingress
#     namespace: {{ .Values.stacks.ingress.namespaceInternal }}
#   needs:
#   - "{{ .Values.stacks.ingress.namespaceInternal }}/traefik"
#   values:
#   - resources:
#     - apiVersion: traefik.containo.us/v1alpha1
#       kind: IngressRoute
#       metadata:
#         name: traefik-dashboard
#       spec:
#         entryPoints:
#           - web
#         routes:
#           - match: Host(`traefik.{{ .Values.stacks.ingress.zoneInternal }}`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
#             kind: Rule
#             services:
#               - name: api@internal
#                 kind: TraefikService
