helmDefaults:
  tillerless: true
  tillerNamespace: platform
  atomic: true
  verify: false
  wait: false
  timeout: 900
  recreatePods: false
  force: false

repositories:
- name: rancher
  url: https://releases.rancher.com/server-charts/latest

###############
## Rancher chart
## Description: 
releases:
- name: namespace-rancher
  chart: ../charts/namespace/chart/namespace
  namespace: kube-system
  labels:
    chart: namespace-rancher
    component: "rancher"
    namespace: {{ env "STACK_RANCHER_NAMESPACE" | default "cattle-system" }}
  wait: true
  installed: {{ env "STACK_RANCHER" | default "true" }}
  values:
  - namespaces:
    - {{ env "STACK_RANCHER_NAMESPACE" | default "cattle-system" }}

## rancher Deployment
- name: rancher
  namespace: {{ env "STACK_RANCHER_NAMESPACE" | default "cattle-system" }}
  installed: {{ env "STACK_RANCHER" | default "true" }}
  chart: rancher/rancher
  labels:
    chart: rancher
    component: rancher
    namespace: {{ env "STACK_RANCHER_NAMESPACE" | default "cattle-system" }}
  needs:
    - kube-system/namespace-rancher
  values:
  - hostname: rancher.{{ .Environment.Values.overrides.fqdn | default "micro.svc" }}
    ingress:
      extraAnnotations:
        kubernetes.io/ingress.class: {{ env "STACK_INGRESS_INT_CLASS" | default "internal" }}
        certmanager.k8s.io/cluster-issuer: default
# - name: ingress-rancher
#   namespace: {{ env "STACK_RANCHER_NAMESPACE" | default "cattle-system" }}
#   chart: {{ env "ARCHTYPE_CHART" | default "../charts/archtype" }}
#   installed: {{ env "STACK_RANCHER" | default "true" }}
#   labels:
#     chart: "ingress-rancher"
#     component: "ingress"
#     namespace: {{ env "STACK_RANCHER_NAMESPACE" | default "cattle-system" }}
#   needs:
#     - kube-system/namespace-rancher
#   values:
#   - project:
#       team: {{ env "TEAM" | default "team1" }}
#       stage: {{ env "STAGE" | default "dev" }}
#       target: {{ env "TARGET" | default "cicd" }}
#       client: {{ env "CLIENT" | default "client1" }}
#     ingressInternalClass: {{ env "STACK_INGRESS_INT_CLASS" | default "internal" }}
#     ingressTests: false
#     ingress:
#       enabled: true
#       hosts:
#       - name: rancher.{{ .Environment.Values.overrides.fqdn | default "micro.svc" }}
#         config:
#           http:
#             paths:
#             - path: "/"
#               backend:
#                 serviceName: rancher
#                 servicePort: 9092
