---
bases:
- ../config/environments.yaml
- ../config/helmdefaults.yaml
- ../config/repositories.yaml
---

releases:
- name: dnsproxy
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.7" }}
  namespace: kube-system
  condition: ingress.enabled
  installed: true
  labels:
    chart: dnsproxy
    component: service
    namespace: kube-system
  values:
  - zone: internal
    app: dnsproxy
    service:
      enabled: true
      type: LoadBalancer
      ports:
        dns:
          protocol: UDP
          port: 53
          targetPort: 53
      selector:
        k8s-app: "kube-dns"
