## Install Hashicorp argocd with Consul backend
---
bases:
- ../config/environments.yaml
- ../config/{{ .Environment.Name }}/helmdefaults.yaml
- ../config/{{ .Environment.Name }}/repositories.yaml
---

releases:
- name: namespace-argocd
  chart: {{ .Values.archetype.chart }}
  version: {{ .Values.archetype.version }}
  namespace: kube-system
  condition: argocd.enabled
  installed: true
  wait: true
  labels:
    chart: namespace-argocd
    component: argocd
    namespace: kube-system
  values:
  - app: argocd
    namespace:
      enabled: true
      name: {{ .Values.argocd.namespace }}

## argocd Deployment
# Values: https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/values.yaml
- name: argo-cd
  chart: {{ .Values.argocd.chart }}
  namespace: {{ .Values.argocd.namespace }}
  #version: {{ .Values.argocd.version }}
  condition: argocd.enabled
  installed: true
  labels:
    chart: argocd
    component: argocd
    namespace: {{ .Values.argocd.namespace }}
  needs:
    - kube-system/namespace-argocd
  values:
  - server:
      # Setup server as insecure so that we can use traefik to expose ingress
      # https://argoproj.github.io/argo-cd/operator-manual/ingress/
      extraArgs:
      - --insecure
      # Additional configmap entry for helmfile custom plugin
      # https://github.com/travisghansen/argo-cd-helmfile
      config:
        # Argo CD's externally facing base URL (optional). Required when configuring SSO
        url: https://argocd.{{ .Values.ingress.internal.zone }}
        application.instanceLabelKey: argocd.argoproj.io/instance
        configManagementPlugins: |
          - name: helmfile
            init:
              command: ["argo-cd-helmfile.sh"]
              args: ["init"]
            generate:
              command: ["argo-cd-helmfile.sh"]
              args: ["generate"]
    repoServer:
      volumes:
      - name: custom-tools
        emptyDir: {}
      initContainers:
      - name: download-tools
        image: alpine:3.8
        command: [sh, -c]
        args:
          - wget -qO /custom-tools/argo-cd-helmfile.sh https://raw.githubusercontent.com/travisghansen/argo-cd-helmfile/master/src/argo-cd-helmfile.sh &&
            chmod +x /custom-tools/argo-cd-helmfile.sh &&
            wget -qO /custom-tools/helmfile https://github.com/roboll/helmfile/releases/download/v0.116.0/helmfile_linux_amd64 &&
            chmod +x /custom-tools/helmfile
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools
      volumeMounts:
      - mountPath: /usr/local/bin/argo-cd-helmfile.sh
        name: custom-tools
        subPath: argo-cd-helmfile.sh
      - mountPath: /usr/local/bin/helmfile
        name: custom-tools
        subPath: helmfile

- name: ingress-argocd
  chart: {{ .Values.raw.chart }}
  version: {{ .Values.raw.version }}
  namespace: {{ .Values.argocd.namespace }}
  condition: ingress.enabled
  installed: true
  needs:
  - kube-system/namespace-argocd
  - {{ .Values.argocd.namespace }}/argo-cd
  labels:
    chart: ingress-argocd
    component: ingress
    namespace: {{ .Values.argocd.namespace }}
  values:
  - resources:
    - apiVersion: traefik.containo.us/v1alpha1
      kind: IngressRoute
      metadata:
        name: argocd-server-ingress
      spec:
        entryPoints:
          - websecure
        routes:
          - match: Host(`argocd.{{ .Values.ingress.internal.zone }}`)
            kind: Rule
            services:
              - name: argo-cd-argocd-server
                port: 80
        tls:
          certResolver: default
          options: {}
