---
bases:
- ../config/environments.yaml
- ../config/{{ .Environment.Name }}/helmdefaults.yaml
- ../config/{{ .Environment.Name }}/repositories.yaml
---

releases:
- name: {{ .Values.rbacmanager.name }}-namespace
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.1" }}
  namespace: kube-system
  condition: rbacmanager.enabled
  installed: true
  wait: true
  labels:
    chart: {{ .Values.rbacmanager.name }}-namespace
    component: {{ .Values.rbacmanager.name }}
    namespace: kube-system
  values:
  - app: {{ .Values.rbacmanager.name }}
    namespace:
      enabled: true
      name: {{ .Values.rbacmanager.namespace }}
      annotations:
        certmanager.k8s.io/disable-validation: "true"

- name: {{ .Values.rbacmanager.name }}
  chart: {{ .Values.rbacmanager.chart }}
  namespace: {{ .Values.rbacmanager.namespace }}
  version: {{ .Values.rbacmanager.version }}
  condition: rbacmanager.enabled
  installed: true
  labels:
    chart: {{ .Values.rbacmanager.name }}
    component: {{ .Values.rbacmanager.name }}
    namespace: {{ .Values.rbacmanager.namespace }}
  needs:
  - kube-system/{{ .Values.rbacmanager.name }}-namespace

- name: {{ .Values.rbacmanager.name }}-rolebinding
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  namespace: {{ .Values.rbacmanager.namespace }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.1" }}
  condition: rbacmanager.enabled
  installed: true
  labels:
    chart: rolebinding-{{ .Values.rbacmanager.name }}
    component: {{ .Values.rbacmanager.name }}
    namespace: {{ .Values.rbacmanager.namespace }}
  needs:
  - {{ .Values.rbacmanager.namespace }}/{{ .Values.rbacmanager.name }}
  values:
  - app: rolebinding-{{ .Values.rbacmanager.name }}
    clusterRole:
      enabled: true
      name: {{ .Values.rbacmanager.name }}-cluster-admin
    clusterRoleBinding:
      enabled: true
      roleName: {{ .Values.rbacmanager.name }}-cluster-admin
      serviceAccountNamespace: {{ .Values.rbacmanager.namespace }}
      serviceAccountName: default
