---
bases:
- ../config/environments.yaml
- ../config/helmdefaults.yaml
- ../config/repositories.yaml
---

## Traefik
# Values - https://github.com/containous/traefik-helm-chart/blob/master/traefik/values.yaml
# Dashboard - http://traefik.int.micro.svc/dashboard/#/
releases:
- name: traefik-namespace
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.2" }}
  namespace: kube-system
  condition: ingress.enabled
  installed: true
  wait: true
  labels:
    chart: traefik-namespace
    component: traefik
    namespace: kube-system
  values:
  - app: traefik
    namespace:
      enabled: true
      name: {{ .Values | getOrNil "ingress.internal.namespace" | default "ingress-int" }}

## traefik Deployment
- name: traefik
  chart: {{ .Values | getOrNil "traefik.chart" | default "traefik/traefik" }}
  version: {{ .Values | getOrNil "traefik.version" | default "8.2.1" }}
  namespace: {{ .Values | getOrNil "ingress.internal.namespace" | default "ingress-int" }}
  condition: ingress.enabled
  installed: true
  missingFileHandler: Debug
  labels:
    chart: traefik
    component: traefik
    namespace: {{ .Values | getOrNil "ingress.internal.namespace" | default "ingress-int" }}
  needs:
  - kube-system/traefik-namespace
  values:
  - globalArguments:
    - "--global.checknewversion=false"
    - "--global.sendanonymoususage=false"
    - "--api.insecure=true"
    additionalArguments:
      - "--providers.kubernetesingress=true"
      - "--providers.kubernetesingress.ingressclass={{ .Values | getOrNil "ingress.internal.class" | default "internal" }}"
      - "--log.level={{ .Values | getOrNil "traefik.loglevel" | default "INFO" }}"
      - "--accesslog={{ .Values | getOrNil "traefik.accesslog" | default "true" }}"
      - "--metrics.prometheus={{ .Values | getOrNil "prometheusoperator.enabled" | default "true" }}"
      - "--tracing={{ .Values | getOrNil "traefik.tracing" | default "false" }}"
    ingressRoute:
      dashboard:
        enabled: false
        annotations:
          "cert-manager.io/cluster-issuer": "default"
          "kubernetes.io/ingress.class": "{{ .Values | getOrNil "ingress.internal.class" | default "internal" }}"
          "service.beta.kubernetes.io/local-load-balancer-internal": "true"
    service:
      type: LoadBalancer
      spec:
        externalTrafficPolicy: Cluster
        {{- if (ne .Values.ingress.internal.ip "") | default "" }}
        loadBalancerIP: "{{ .Values.ingress.internal.ip }}"
        {{- end }}
      annotations:
        "prometheus.io/scrape": "{{ .Values | getOrNil "prometheusoperator.enabled" | default "false" }}"
        "prometheus.io/port": "9913"
        "service.beta.kubernetes.io/{{ .Values | getOrNil "cloud" | default "local" }}-load-balancer-internal": "true"
    ports:
      traefik:
        expose: true
    nodeSelector:
      ingress-ready: "true"
  - "../config/{{ .Environment.Name }}/traefik.override.yaml"

- name: traefik-dashboard
  chart: {{ .Values | getOrNil "raw.chart" | default "incubator/raw" }}
  version: {{ .Values | getOrNil "raw.version" | default "0.2.3" }}
  namespace: {{ .Values | getOrNil "ingress.internal.namespace" | default "ingress-int" }}
  condition: traefik.enabled
  installed: true
  labels:
    chart: traefik-dashboard
    component: ingress
    namespace: {{ .Values | getOrNil "ingress.internal.namespace" | default "ingress-int" }}
  needs:
  - "{{ .Values | getOrNil "ingress.internal.namespace" | default "ingress-int" }}/traefik"
  values:
  - resources:
    - apiVersion: traefik.containo.us/v1alpha1
      kind: IngressRoute
      metadata:
        name: traefik-dashboard
      spec:
        entryPoints:
          - web
        routes:
          - match: Host(`traefik.{{ .Values | getOrNil "ingress.internal.zone" | default "int" }}.{{ .Values | getOrNil "dnsRoot" | default "micro.svc" }}`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
            kind: Rule
            services:
              - name: api@internal
                kind: TraefikService
