---
bases:
- ../config/environments.yaml
- ../config/helmdefaults.yaml
- ../config/repositories.yaml
---

releases:
- name: {{ .Values | getOrNil "consul.name" | default "consul" }}-namespace
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.1" }}
  namespace: kube-system
  condition: consul.enabled
  installed: true
  wait: true
  labels:
    chart: {{ .Values | getOrNil "consul.name" | default "consul" }}-namespace
    component: {{ .Values | getOrNil "consul.name" | default "consul" }}
    namespace: kube-system
  values:
  - app: {{ .Values | getOrNil "consul.name" | default "consul" }}
    namespace:
      enabled: true
      name: {{ .Values | getOrNil "consul.namespace" | default "consul" }}

- name: {{ .Values | getOrNil "consul.name" | default "consul" }}
  chart: {{ .Values | getOrNil "consul.chart" | default "consul/consul" }}
  version: {{ .Values | getOrNil "consul.version" | default "0.21.0" }}
  namespace: {{ .Values | getOrNil "consul.namespace" | default "consul" }}
  condition: consul.enabled
  installed: true
  labels:
    chart: {{ .Values | getOrNil "consul.name" | default "consul" }}
    component: {{ .Values | getOrNil "consul.name" | default "consul" }}
    namespace: {{ .Values | getOrNil "consul.namespace" | default "consul" }}
  needs:
    - kube-system/{{ .Values | getOrNil "consul.name" | default "consul" }}-namespace
  values:
  - dns:
      enabled: false
    client:
      enabled: true
    server:
      replicas: 1
      bootstrapExpect: 1
      disruptionBudget:
        maxUnavailable: 0
      storage: 2Gi
    ui:
      enabled: true
    service:
      type: LoadBalancer
    consulNamespaces:
      consulDestinationNamespace: kube
      mirroringK8S: false

- name: {{ .Values | getOrNil "consul.name" | default "consul" }}-ingress
  namespace: {{ .Values | getOrNil "consul.namespace" | default "consul" }}
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.1" }}
  condition: ingress.enabled
  installed: true
  needs:
  - kube-system/{{ .Values | getOrNil "consul.name" | default "consul" }}-namespace
  - {{ .Values | getOrNil "consul.namespace" | default "consul" }}/{{ .Values | getOrNil "consul.name" | default "consul" }}
  labels:
    chart: {{ .Values | getOrNil "consul.name" | default "consul" }}-ingress
    component: ingress
    namespace: {{ .Values | getOrNil "consul.namespace" | default "consul" }}
  values:
  - zone: internal
    app: consul
    dnsRoot: micro.svc
    ingressClassMap:
      internal: {{ .Values | getOrNil "ingress.internal.class" | default "internal" }}
    ingress:
      enabled: true
      tlsEnabled: true
      hosts:
      - secretName: {{ .Values | getOrNil "consul.name" | default "consul" }}-ingress
        config:
          http:
            paths:
            - path: "/"
              backend:
                serviceName: {{ .Values | getOrNil "consul.name" | default "consul" }}-consul-ui
                servicePort: 80
