---
bases:
- ../config/environments.yaml
- ../config/helmdefaults.yaml
- ../config/{{ .Environment.Name }}/repositories.yaml
---

###############
## Rancher Deployment
releases:
- name: namespace-rancher
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.1" }}
  namespace: kube-system
  labels:
    chart: namespace-rancher
    component: rancher
    namespace: kube-system
  wait: true
  installed: true
  values:
  - app: rancher
    namespace:
      enabled: true
      name: cattle-system

## rancher Deployment
- name: rancher
  namespace: cattle-system
  installed: true
  chart: rancher/rancher
  labels:
    chart: rancher
    component: rancher
    namespace: cattle-system
  needs:
    - kube-system/namespace-rancher
  values:
  - hostname: rancher.{{ .Values | getOrNil "ingress.internal.zone" | default "int.micro.svc" }}
    # ingress:
    #   extraAnnotations:
    #     kubernetes.io/ingress.class: {{ .Values | getOrNil "ingress.internal.class" | default "internal" }}

