---
bases:
- ../config/environments.yaml
- ../config/helmdefaults.yaml
- ../config/repositories.yaml
---

releases:
- name: rbacmanager-namespace
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.8" }}
  namespace: kube-system
  condition: rbacmanager.enabled
  installed: true
  wait: true
  labels:
    chart: rbacmanager-namespace
    component: rbacmanager
    namespace: kube-system
  values:
  - app: rbacmanager
    namespace:
      enabled: true
      name: {{ .Values | getOrNil "rbacmanager.namespace" | default "rbacmanager" }}
      annotations:
        certmanager.k8s.io/disable-validation: "true"

- name: rbacmanager
  chart: {{ .Values | getOrNil "rbacmanager.chart" | default "reactiveops-stable/rbac-manager" }}
  namespace: {{ .Values | getOrNil "rbacmanager.namespace" | default "rbacmanager" }}
  version: {{ .Values | getOrNil "rbacmanager.version" | default "1.5.4" }}
  condition: rbacmanager.enabled
  installed: true
  missingFileHandler: Debug
  labels:
    chart: rbacmanager
    component: rbacmanager
    namespace: {{ .Values | getOrNil "rbacmanager.namespace" | default "rbacmanager" }}
  needs:
  - kube-system/rbacmanager-namespace
  values:
  - "../config/{{ .Environment.Name }}/rbacmanager.override.yaml"

- name: rbacmanager-rolebinding
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  namespace: {{ .Values | getOrNil "rbacmanager.namespace" | default "rbacmanager" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.8" }}
  condition: rbacmanager.enabled
  installed: true
  labels:
    chart: rbacmanager-rolebinding
    component: rbacmanager
    namespace: {{ .Values | getOrNil "rbacmanager.namespace" | default "rbacmanager" }}
  needs:
  - {{ .Values | getOrNil "rbacmanager.namespace" | default "rbacmanager" }}/rbacmanager
  values:
  - app: rbacmanager-rolebinding
    clusterRole:
      enabled: true
      name: rbacmanager-cluster-admin
    clusterRoleBinding:
      enabled: true
      roleName: rbacmanager-cluster-admin
      serviceAccountNamespace: {{ .Values | getOrNil "rbacmanager.namespace" | default "rbacmanager" }}
      serviceAccountName: default
