---
bases:
- ../config/environments.yaml
- ../config/helmdefaults.yaml
- ../config/repositories.yaml
---

## HomeAssistant 
# Link: https://github.com/helm/charts/blob/master/stable/home-assistant/values.yaml
releases:
- name: homeassistant-namespace
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.8" }}
  namespace: kube-system
  condition: homeassistant.enabled
  installed: true
  wait: true
  labels:
    chart: homeassistant-namespace
    component: homeassistant
    namespace: kube-system
  values:
  - app: homeassistant
    namespace:
      enabled: true
      name: {{ .Values | getOrNil "homeassistant.namespace" | default "homeassistant" }}

- name: homeassistant
  chart: {{ .Values | getOrNil "homeassistant.chart" | default "stable/home-assistant" }}
  version: {{ .Values | getOrNil "homeassistant.version" | default "0.13.3" }}
  namespace: {{ .Values | getOrNil "homeassistant.namespace" | default "homeassistant" }}
  condition: homeassistant.enabled
  installed: true
  missingFileHandler: Debug
  labels:
    chart: homeassistant
    component: homeassistant
    namespace: {{ .Values | getOrNil "homeassistant.namespace" | default "homeassistant" }}
  needs:
    - kube-system/homeassistant-namespace
  values:
  - image:
      repository: homeassistant/home-assistant
      tag: latest
    persistence:
      enabled: true
      size: 40Gi
    hostNetwork: false
    git:
      enabled: false
      user:
        name: ""
        email: ""
    vscode:
      enabled: true
    configurator:
      enabled: true
    zwave:
      enabled: false
      device: ttyACM0
    # Mount devices or folders from the host machine. Can be used for USB device mounting.
    hostMounts: []
    monitoring:
      enabled: {{ .Values | getOrNil "prometheusoperator.enabled" | default "false" }}
      serviceMonitor:
        enabled: {{ .Values | getOrNil "prometheusoperator.enabled" | default "false" }}
    appdaemon:
      enabled: false
  - "../config/{{ .Environment.Name }}/homeassistant.override.yaml"

- name: homeassistant-dashboard-ingress
  namespace: {{ .Values | getOrNil "homeassistant.namespace" | default "homeassistant" }}
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.8" }}
  condition: ingress.enabled
  installed: true
  needs:
  - kube-system/homeassistant-namespace
  - {{ .Values | getOrNil "homeassistant.namespace" | default "homeassistant" }}/homeassistant
  labels:
    chart: homeassistant-dashboard-ingress
    component: homeassistant
    namespace: {{ .Values | getOrNil "homeassistant.namespace" | default "homeassistant" }}
  values:
  - app: haas
    dnsRoot: {{ .Values | getOrNil "dnsRoot" | default "micro.svc" }}
    zone: {{ .Values | getOrNil "homeassistant.zone" | default "internal" }}
    ingress:
      enabled: true
      tlsEnabled: true
      hosts:
      - secretName: homeassistant-dashboard-ingress
        paths:
        - path: "/"
          backend:
            serviceName: homeassistant-home-assistant
            servicePort: 8123

- name: homeassistant-vscode-ingress
  namespace: {{ .Values | getOrNil "homeassistant.namespace" | default "homeassistant" }}
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.8" }}
  condition: ingress.enabled
  installed: true
  needs:
  - kube-system/homeassistant-namespace
  - {{ .Values | getOrNil "homeassistant.namespace" | default "homeassistant" }}/homeassistant
  labels:
    chart: homeassistant-vscode-ingress
    component: homeassistant
    namespace: {{ .Values | getOrNil "homeassistant.namespace" | default "homeassistant" }}
  values:
  - app: vscode
    dnsRoot: {{ .Values | getOrNil "dnsRoot" | default "micro.svc" }}
    zone: {{ .Values | getOrNil "homeassistant.zone" | default "internal" }}
    ingress:
      enabled: true
      tlsEnabled: true
      hosts:
      - secretName: homeassistant-vscode-ingress
        paths:
        - path: "/"
          backend:
            serviceName: homeassistant-home-assistant
            servicePort: 80

- name: homeassistant-configurator-ingress
  namespace: {{ .Values | getOrNil "homeassistant.namespace" | default "homeassistant" }}
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.8" }}
  condition: ingress.enabled
  installed: true
  needs:
  - kube-system/homeassistant-namespace
  - {{ .Values | getOrNil "homeassistant.namespace" | default "homeassistant" }}/homeassistant
  labels:
    chart: homeassistant-configurator-ingress
    component: homeassistant
    namespace: {{ .Values | getOrNil "homeassistant.namespace" | default "homeassistant" }}
  values:
  - app: configurator
    dnsRoot: {{ .Values | getOrNil "dnsRoot" | default "micro.svc" }}
    zone: {{ .Values | getOrNil "homeassistant.zone" | default "internal" }}
    ingress:
      enabled: true
      tlsEnabled: true
      hosts:
      - secretName: homeassistant-configurator-ingress
        paths:
        - path: "/"
          backend:
            serviceName: homeassistant-home-assistant
            servicePort: 3218
