helmDefaults:
  tillerless: true
  tillerNamespace: platform
  atomic: true
  verify: false
  wait: false
  timeout: 900
  recreatePods: false
  force: false

repositories:
- name: traefik
  url: "git+https://github.com/containous/traefik-helm-chart@/traefik"

###############
## traefik
releases:
{{- if eq (env "HELM_VERSION" | default "2") "3" }}
- name: namespace-traefik
  # Helm 3 needs to put deployment info into a namespace. As this creates a namespace it will not exist yet so we use 'kube-system' 
  #  which should exist in all clusters.
  chart: ../charts/namespace/chart/namespace
  namespace: kube-system
  labels:
    chart: namespace-traefik
    component: "traefik"
    namespace: "{{ env "STACK_INGRESS_INT_NAMESPACE" | default "ingress-int" }}"
  wait: true
  installed: true
  values:
  - namespaces:
    - {{ env "STACK_INGRESS_INT_NAMESPACE" | default "ingress-int" }}
{{- end }}

## traefik Deployment
- name: traefik
  namespace: "{{ env "STACK_INGRESS_INT_NAMESPACE" | default "ingress-int" }}"
  installed: {{ env "STACK_INGRESS_INT" | default "true" }}
  chart: traefik/traefik
  labels:
    chart: traefik
    component: traefik
    namespace: "{{ env "STACK_INGRESS_INT_NAMESPACE" | default "ingress-int" }}"
{{- if eq (env "HELM_VERSION" | default "2") "3" }}
  needs:
    - kube-system/namespace-traefik
{{- end }}
  values:
  - additional:
      sendAnonymousUsage: false
  - service:
      annotations:
        "prometheus.io/scrape": "true"
        "prometheus.io/port": "9913"
        "service.beta.kubernetes.io/{{ env "CLOUD" | default "local" }}-load-balancer-internal": "true"
      type: LoadBalancer
      spec:
        externalTrafficPolicy: Cluster
        loadBalancerIP: "{{ env "INGRESS_INTERNALIP" | default "127.0.0.1" }}"
    additionalArguments:
      - "--providers.kubernetesingress"
      - "--providers.kubernetesingress.ingressclass={{ env "STACK_INGRESS_INT_CLASS" | default "internal" }}"
    dashboard:
      enable: true
      ingressRoute: true
      domain: traefik.{{ .Environment.Values.overrides.fqdn | default "micro.svc" }}
    web:
      nodePort: 32080
    websecure:
      nodePort: 32443
