helmDefaults:
  tillerless: true
  tillerNamespace: platform
  atomic: false
  verify: false
  wait: true
  timeout: 900
  recreatePods: true
  force: true

releases:
- name: "kafkahq"
  namespace: "database"
  chart: "../charts/kafkahq"
  #version: 0.0.2
  labels:
    chart: kafkahq
    component: config
    namespace: database
  values:
  - Target: '{{ env "TARGET" | default "cicd" }}'

- name: ingress-kafkahq
  namespace: "database"
  chart: {{ env "ARCHTYPE_CHART" | default "../charts/archtype" }}
  labels:
    chart: ingress-kafkahq
    component: ingress
    namespace: database
  values:
  - project:
      team: {{ env "TEAM" | default "ops" }}
      target: {{ env "TARGET" | default "cicd" }}
      client: {{ env "CLIENT" | default "client1" }}
    ingressInternalClass: {{ env "STACK_INGRESS_INT_CLASS" | default "internal" }}
    ingress:
      enabled: true
      hosts:
      - name: kafkahq.{{ .Environment.Values.overrides.fqdn | default "micro.svc" }}
        config:
          http:
            paths:
            - path: "/"
              backend:
                serviceName: kafkahq-svc
                servicePort: 8080