---
bases:
- ../config/environments.yaml
- ../config/helmdefaults.yaml
- ../config/repositories.yaml
---

## Consul deployment
# Values - https://www.consul.io/docs/k8s/helm.html
releases:
- name: consul-namespace
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.8" }}
  namespace: kube-system
  condition: consul.enabled
  installed: true
  wait: true
  labels:
    chart: consul-namespace
    component: consul
    namespace: kube-system
  values:
  - app: consul
    namespace:
      enabled: true
      name: {{ .Values | getOrNil "consul.namespace" | default "consul" }}

- name: consul
  chart: {{ .Values | getOrNil "consul.chart" | default "consul/consul" }}
  version: {{ .Values | getOrNil "consul.version" | default "0.21.0" }}
  namespace: {{ .Values | getOrNil "consul.namespace" | default "consul" }}
  condition: consul.enabled
  installed: true
  missingFileHandler: Debug
  labels:
    chart: consul
    component: consul
    namespace: {{ .Values | getOrNil "consul.namespace" | default "consul" }}
  needs:
    - kube-system/consul-namespace
  values:
  - dns:
      enabled: false
    client:
      enabled: true
    syncCatalog:
      enabled: true
    server:
      replicas: 1
      bootstrapExpect: 1
      disruptionBudget:
        maxUnavailable: 0
      storage: 2Gi
    ui:
      enabled: true
    # service:
    #   type: LoadBalancer
    consulNamespaces:
      consulDestinationNamespace: kube
      mirroringK8S: false
  - "../config/{{ .Environment.Name }}/consul.override.yaml"

- name: consul-ui-ingress
  namespace: {{ .Values | getOrNil "consul.namespace" | default "consul" }}
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.8" }}
  condition: ingress.enabled
  installed: true
  needs:
  - kube-system/consul-namespace
  - {{ .Values | getOrNil "consul.namespace" | default "consul" }}/consul
  labels:
    chart: consul-ui-ingress
    component: ingress
    namespace: {{ .Values | getOrNil "consul.namespace" | default "consul" }}
  values:
  - zone: internal
    app: consul-ui
    dnsRoot: {{ .Values | getOrNil "dnsRoot" | default "micro.svc" }}
    ingressClassMap:
      internal: {{ .Values | getOrNil "ingress.internal.class" | default "internal" }}
    ingress:
      enabled: true
      tlsEnabled: true
      hosts:
      - secretName: consul-ui-ingress
        paths:
        - path: "/"
          backend:
            serviceName: consul-consul-ui
            servicePort: 80

- name: consul-ingress
  namespace: {{ .Values | getOrNil "consul.namespace" | default "consul" }}
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.8" }}
  condition: ingress.enabled
  installed: true
  needs:
  - kube-system/consul-namespace
  - {{ .Values | getOrNil "consul.namespace" | default "consul" }}/consul
  labels:
    chart: consul-ingress
    component: ingress
    namespace: {{ .Values | getOrNil "consul.namespace" | default "consul" }}
  values:
  - zone: internal
    app: consul
    dnsRoot: {{ .Values | getOrNil "dnsRoot" | default "micro.svc" }}
    ingressClassMap:
      internal: {{ .Values | getOrNil "ingress.internal.class" | default "internal" }}
    ingress:
      enabled: true
      tlsEnabled: true
      hosts:
      - secretName: consul-ingress
        paths:
        - path: "/"
          backend:
            serviceName: consul-consul-server
            servicePort: 8500
