---
bases:
- ../config/environments.yaml
- ../config/{{ .Environment.Name }}/helmdefaults.yaml
- ../config/{{ .Environment.Name }}/repositories.yaml
---

releases:
- name: namespace-{{ .Values.vault.name }}
  chart: {{ .Values.archetype.chart }}
  version: {{ .Values.archetype.version }}
  namespace: kube-system
  wait: true
  condition: vault.enabled
  installed: true
  labels:
    chart: namespace-{{ .Values.vault.name }}
    component: vault
    namespace: kube-system
  values:
  - app: {{ .Values.vault.name }}
    namespace:
      enabled: true
      name: {{ .Values.vault.namespace }}

## Vault Deployment
- name: {{ .Values.vault.name }}
  chart: {{ .Values.vault.chart }}
  version: {{ .Values.vault.version }}
  namespace: {{ .Values.vault.namespace }}
  condition: vault.enabled
  installed: true
  labels:
    chart: {{ .Values.vault.name }}
    component: vault
    namespace: {{ .Values.vault.namespace }}
  needs:
    - kube-system/namespace-{{ .Values.vault.name }}
  values:
  - server:
      # affinity: ""
      ha:
        enabled: true
      service: 
        type: LoadBalancer
      dev:
        enabled: true
      dataStorage:
        enabled: true
        size: 2Gi
    ui:
      enabled: true

- name: ingress-{{ .Values.vault.name }}
  chart: {{ .Values.archetype.chart }}
  version: {{ .Values.archetype.version }}
  namespace: {{ .Values.vault.namespace }}
  condition: ingress.enabled
  installed: true
  needs:
  - kube-system/namespace-{{ .Values.vault.name }}
  - {{ .Values.vault.namespace }}/{{ .Values.vault.name }}
  labels:
    chart: ingress-{{ .Values.vault.name }}
    component: ingress
    namespace: {{ .Values.vault.namespace }}
  values:
  - zone: internal
    app: {{ .Values.vault.name }}
    ingressClassMap:
      internal: {{ .Values.ingress.internal.class }}
    ingress:
      enabled: true
      tlsEnabled: true
      hosts:
      - name: vault.{{ .Values.ingress.internal.zone }}
        secretName: ingress-vault-dashboard
        config:
          http:
            paths:
            - path: "/"
              backend:
                serviceName: vault-ui
                servicePort: 8200

## Role binding needed to do vault auth
- name: rolebinding-{{ .Values.vault.name }}
  chart: {{ .Values.raw.chart }}
  version: {{ .Values.raw.version }}
  namespace: {{ .Values.vault.namespace }}
  condition: vault.enabled
  installed: true
  needs:
  - {{ .Values.vault.namespace }}/{{ .Values.vault.name }}
  values:
  - resources:
    - apiVersion: rbacmanager.reactiveops.io/v1beta1
      kind: RBACDefinition
      metadata:
        name: rolebinding-{{ .Values.vault.name }}
      rbacBindings:
      - name: example-service-account
        subjects:
          - kind: ServiceAccount
            name: vault
            namespace: {{ .Values.vault.namespace }}
        clusterRoleBindings:
          - clusterRole: system:auth-delegator