---
bases:
- ../config/environments.yaml
- ../config/helmdefaults.yaml
- ../config/repositories.yaml
---

## Installs istio
releases:
- name: istio-namespace
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.2" }}
  namespace: kube-system
  condition: istio.enabled
  installed: true
  wait: true
  labels:
    chart: istio-namespace
    component: istio
    namespace: kube-system
  values:
  - app: istio
    namespace:
      enabled: true
      name: {{ .Values | getOrNil "istio.namespace" | default "istio-system" }}

- name: istio
  chart: {{ .Values | getOrNil "raw.chart" | default "incubator/raw" }}
  namespace: {{ .Values | getOrNil "istio.namespace" | default "istio-system" }}
  version: {{ .Values | getOrNil "raw.version" | default "0.2.3" }}
  condition: istio.enabled
  installed: true
  missingFileHandler: Debug
  labels:
    chart: istio
    component: istio
    namespace: {{ .Values | getOrNil "istio.namespace" | default "istio-system" }}
  needs:
  - kube-system/istio-namespace
  values:
  - resources:
    - apiVersion: install.istio.io/v1alpha1
      kind: IstioOperator
      metadata:
        name: {{ .Values | getOrNil "istio.name" | default "istiocontrolplane" }}
      spec:
        profile: {{ .Values | getOrNil "istio.profile" | default "demo" }}
  - "../config/{{ .Environment.Name }}/istio.override.yaml"

- name: istio-dashboard-ingress
  namespace: {{ .Values | getOrNil "istio.namespace" | default "istio" }}
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.2" }}
  condition: ingress.enabled
  installed: true
  needs:
  - {{ .Values | getOrNil "istio.namespace" | default "istio-system" }}/istio
  labels:
    chart: istio-dashboard-ingress
    component: istio
    namespace: {{ .Values | getOrNil "istio.namespace" | default "istio-system" }}
  values:
  - app: istio
    dnsRoot: {{ .Values | getOrNil "dnsRoot" | default "micro.svc" }}
    zone: {{ .Values | getOrNil "istio.zone" | default "internal" }}
    istio:
      gateway:
        enabled: true
    ingress:
      enabled: true
      type: istio
      hosts:
      - name: prometheus
        paths:
        - path: "/"
          backend:
            serviceName: prometheus
            servicePort: 9090
      - name: kiali
        paths:
        - path: "/"
          backend:
            serviceName: kiali
            servicePort: 20001
      - name: grafana
        paths:
        - path: "/"
          backend: 
            serviceName: grafana
            servicePort: 3000

