---
bases:
- ../config/environments.yaml
- ../config/{{ .Environment.Name }}/helmdefaults.yaml
- ../config/{{ .Environment.Name }}/repositories.yaml
---

###############
## Rancher Deployment
releases:
- name: namespace-rancher
  chart: {{ .Values.archetype.chart }}
  version: {{ .Values.archetype.version }}
  namespace: kube-system
  labels:
    chart: namespace-rancher
    component: rancher
    namespace: kube-system
  wait: true
  installed: true
  values:
  - app: rancher
    namespace:
      enabled: true
      name: cattle-system

## rancher Deployment
- name: rancher
  namespace: cattle-system
  installed: true
  chart: rancher/rancher
  labels:
    chart: rancher
    component: rancher
    namespace: cattle-system
  needs:
    - kube-system/namespace-rancher
  values:
  - hostname: rancher.{{ .Values.ingress.internal.zone }}
    # ingress:
    #   extraAnnotations:
    #     kubernetes.io/ingress.class: {{ .Values.ingress.internal.class }}

