---
bases:
- ../config/environments.yaml
- ../config/{{ .Environment.Name }}/helmdefaults.yaml
- ../config/{{ .Environment.Name }}/repositories.yaml
---

releases:
- name: {{ .Values.certmanager.name }}-namespace
  chart: {{ .Values.archetype.chart }}
  version: {{ .Values.archetype.version }}
  namespace: kube-system
  condition: certmanager.enabled
  installed: true
  wait: true
  labels:
    chart: {{ .Values.certmanager.name }}-namespace
    component: {{ .Values.certmanager.name }}
    namespace: kube-system
  values:
  - app: {{ .Values.certmanager.name }}
    namespace:
      enabled: true
      name: {{ .Values.certmanager.namespace }}
      annotations:
        certmanager.k8s.io/disable-validation: "true"

- name: {{ .Values.certmanager.name }}
  chart: {{ .Values.certmanager.chart }}
  namespace: {{ .Values.certmanager.namespace }}
  version: {{ .Values.certmanager.version }}
  condition: certmanager.enabled
  installed: true
  wait: true
  labels:
    chart: {{ .Values.certmanager.name }}
    component: {{ .Values.certmanager.name }}
    namespace: {{ .Values.certmanager.namespace }}
  needs:
  - kube-system/{{ .Values.certmanager.name }}-namespace
  values:
  - installCRDs: true
    fullnameOverride: cert-manager
    rbac:
      create: true
    ingressShim:
      defaultIssuerName: default
      defaultIssuerKind: Issuer
    serviceAccount:
      create: true
      name: ""
    prometheus:
      enabled: {{ .Values.monitoring.enabled }}
      servicemonitor:
        enabled: false
    webhook:
      enabled: true
    cainjector:
      enabled: true
    resources:
      limits:
        cpu: "200m"
        memory: "256Mi"
      requests:
        cpu: "50m"
        memory: "128Mi"

- name: {{ .Values.certmanager.name }}-metricsservice
  chart: {{ .Values.raw.chart }}
  namespace: {{ .Values.certmanager.namespace }}
  version: {{ .Values.raw.version }}
  condition: monitoring.enabled
  installed: true
  labels:
    chart: {{ .Values.certmanager.name }}-metricsservice
    component: {{ .Values.certmanager.name }}
    namespace: {{ .Values.certmanager.namespace }}
  needs:
  - kube-system/{{ .Values.certmanager.name }}-namespace
  values:
  - resources:
    - apiVersion: v1
      kind: Service
      metadata:
        name: {{ .Values.certmanager.name }}
        labels:
          app: {{ .Values.certmanager.name }}
      spec:
        type: ClusterIP
        ports:
          - protocol: TCP
            port: 9402
            targetPort: 9402
        selector:
          app.kubernetes.io/name: cert-manager
          app.kubernetes.io/instance: cert-manager

- name: {{ .Values.certmanager.name }}-servicemonitor
  chart: {{ .Values.raw.chart }}
  namespace: {{ .Values.certmanager.namespace }}
  version: {{ .Values.raw.version }}
  condition: monitoring.enabled
  installed: true
  labels:
    chart: cert-manager-servicemonitor
    component: cert-manager
    namespace: {{ .Values.monitoring.namespace }}
  needs:
  - {{ .Values.monitoring.namespace }}/prometheus-operator
  values:
  - resources:
    - apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      metadata:
        name: cert-manager
        namespace: {{ .Values.monitoring.namespace }}
        labels:
          app: cert-manager-servicemonitor
          release: cert-manager-servicemonitor
          prometheus: {{ .Values.prometheus.instance }}
      spec:
        jobLabel: cert-manager
        namespaceSelector:
          matchNames:
          - cert-manager
        selector:
          matchLabels:
            app: cert-manager
            release: cert-manager
        endpoints:
        - targetPort: 9402
          path: /metrics
          interval: 60s
          scrapeTimeout: 30s

- name: {{ .Values.certmanager.name }}-issuers
  chart: {{ .Values.raw.chart }}
  namespace: {{ .Values.certmanager.namespace }}
  version: {{ .Values.raw.version }}
  condition: certmanager.enabled
  installed: true
  labels:
    chart: {{ .Values.certmanager.name }}-issuers
    component: {{ .Values.certmanager.name }}
    namespace: {{ .Values.certmanager.namespace }}
  needs:
  - {{ .Values.certmanager.namespace }}/{{ .Values.certmanager.name }}
  - kube-system/{{ .Values.certmanager.name }}-namespace
  values:
  - resources:
    - apiVersion: cert-manager.io/v1alpha3
      kind: ClusterIssuer
      metadata:
        name: {{ .Values.certmanager.issuerStaging }}
      spec:
        acme:
          server: https://acme-staging-v02.api.letsencrypt.org/directory
          email: {{ .Values.certmanager.email }}
          privateKeySecretRef:
            name: {{ .Values.certmanager.issuerStaging }}
          solvers:
            - http01:
                ingress:
                  class: {{ .Values.ingress.stage.class }}
    - apiVersion: cert-manager.io/v1alpha3
      kind: ClusterIssuer
      metadata:
        name: {{ .Values.certmanager.issuerProduction }}
      spec:
        acme:
          server: https://acme-v02.api.letsencrypt.org/directory
          email: {{ .Values.certmanager.email }}
          privateKeySecretRef:
            name: letsencrypt-prod
          solvers:
            - http01:
                ingress:
                  class: {{ .Values.ingress.external.class }}
    - apiVersion: cert-manager.io/v1alpha3
      kind: ClusterIssuer
      metadata:
        name: {{ .Values.certmanager.issuerDefault }}
      spec:
        selfSigned: {}
