## Prometheus Operator
# site: https://github.com/helm/charts/blob/master/stable/prometheus-operator/values.yaml
---
bases:
- ../config/environments.yaml
- ../config/{{ .Environment.Name }}/helmdefaults.yaml
- ../config/{{ .Environment.Name }}/repositories.yaml
---

releases:
- name: {{ .Values.prometheusoperator.name }}-namespace
  chart: {{ .Values.archetype.chart }}
  version: {{ .Values.archetype.version }}
  namespace: kube-system
  condition: prometheusoperator.enabled
  installed: true
  wait: true
  labels:
    chart: {{ .Values.prometheusoperator.name }}-namespace
    component: {{ .Values.prometheusoperator.name }}
    namespace: kube-system
  values:
  - app: {{ .Values.prometheusoperator.name }}
    namespace:
      enabled: true
      name: {{ .Values.prometheusoperator.namespace }}

- name: {{ .Values.prometheusoperator.name }}
  chart: {{ .Values.prometheusoperator.chart }}
  version: {{ .Values.prometheusoperator.version }}
  namespace: {{ .Values.prometheusoperator.namespace }}
  condition: prometheusoperator.enabled
  installed: true
  labels:
    chart: {{ .Values.prometheusoperator.name }}
    component: {{ .Values.prometheusoperator.name }}
    namespace: {{ .Values.prometheusoperator.namespace }}
  needs:
  - kube-system/{{ .Values.prometheusoperator.name }}-namespace
  values:
  - alertmanager:
      alertmanagerSpec:
        externalUrl: http://alertmanager.{{ .Values.ingress.internal.zone }}
    prometheus:
      prometheusSpec:
        externalUrl: http://prometheus.{{ .Values.ingress.internal.zone }}

- name: {{ .Values.prometheusoperator.name }}-ingress-grafana
  namespace: {{ .Values.prometheusoperator.namespace }}
  chart: {{ .Values.archetype.chart }}
  version: {{ .Values.archetype.version }}
  condition: ingress.enabled
  installed: true
  needs:
  - kube-system/{{ .Values.prometheusoperator.name }}-namespace
  - {{ .Values.prometheusoperator.namespace }}/{{ .Values.prometheusoperator.name }}
  labels:
    chart: {{ .Values.prometheusoperator.name }}-ingress-grafana
    component: {{ .Values.prometheusoperator.name }}
    namespace: {{ .Values.prometheusoperator.namespace }}
  values:
  - zone: internal
    app: grafana
    ingress:
      enabled: true
      tlsEnabled: true
      hosts:
      - secretName: {{ .Values.prometheusoperator.name }}-ingress-grafana
        config:
          http:
            paths:
            - path: "/"
              backend:
                serviceName: {{ .Values.prometheusoperator.name }}-grafana
                servicePort: 80

- name: {{ .Values.prometheusoperator.name }}-ingress-prometheus
  namespace: {{ .Values.prometheusoperator.namespace }}
  chart: {{ .Values.archetype.chart }}
  version: {{ .Values.archetype.version }}
  condition: ingress.enabled
  installed: true
  needs:
  - kube-system/{{ .Values.prometheusoperator.name }}-namespace
  - {{ .Values.prometheusoperator.namespace }}/{{ .Values.prometheusoperator.name }}
  labels:
    chart: {{ .Values.prometheusoperator.name }}-ingress-prometheus
    component: {{ .Values.prometheusoperator.name }}
    namespace: {{ .Values.prometheusoperator.namespace }}
  values:
  - zone: internal
    app: prometheus
    ingress:
      enabled: true
      tlsEnabled: true
      hosts:
      - secretName: {{ .Values.prometheusoperator.name }}-ingress-prometheus
        config:
          http:
            paths:
            - path: "/"
              backend:
                serviceName: prometheus-operated
                servicePort: 9090

- name: {{ .Values.prometheusoperator.name }}-ingress-alertmanager
  namespace: {{ .Values.prometheusoperator.namespace }}
  chart: {{ .Values.archetype.chart }}
  version: {{ .Values.archetype.version }}
  condition: ingress.enabled
  installed: true
  needs:
  - kube-system/{{ .Values.prometheusoperator.name }}-namespace
  - {{ .Values.prometheusoperator.namespace }}/{{ .Values.prometheusoperator.name }}
  labels:
    chart: {{ .Values.prometheusoperator.name }}-ingress-alertmanager
    component: {{ .Values.prometheusoperator.name }}
    namespace: {{ .Values.prometheusoperator.namespace }}
  values:
  - zone: internal
    app: alertmanager
    ingress:
      enabled: true
      tlsEnabled: true
      hosts:
      - secretName: {{ .Values.prometheusoperator.name }}-ingress-alertmanager
        config:
          http:
            paths:
            - path: "/"
              backend:
                serviceName: alertmanager-operated
                servicePort: 9093