---
bases:
- ../config/environments.yaml
- ../config/helmdefaults.yaml
- ../config/{{ .Environment.Name }}/repositories.yaml
---

releases:
- name: {{ .Values | getOrNil "certmanager.name" | default "certmanager" }}-namespace
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.1" }}
  namespace: kube-system
  condition: certmanager.enabled
  installed: true
  wait: true
  labels:
    chart: {{ .Values | getOrNil "certmanager.name" | default "certmanager" }}-namespace
    component: {{ .Values | getOrNil "certmanager.name" | default "certmanager" }}
    namespace: kube-system
  values:
  - app: {{ .Values | getOrNil "certmanager.name" | default "certmanager" }}
    namespace:
      enabled: true
      name: {{ .Values | getOrNil "certmanager.namespace" | default "certmanager" }}
      annotations:
        certmanager.k8s.io/disable-validation: "true"

- name: {{ .Values | getOrNil "certmanager.name" | default "certmanager" }}
  chart: {{ .Values | getOrNil "certmanager.chart" | default "jetstack/cert-manager" }}
  namespace: {{ .Values | getOrNil "certmanager.namespace" | default "certmanager" }}
  version: {{ .Values | getOrNil "certmanager.version" | default "0.15.0" }}
  condition: certmanager.enabled
  installed: true
  wait: true
  labels:
    chart: {{ .Values | getOrNil "certmanager.name" | default "certmanager" }}
    component: {{ .Values | getOrNil "certmanager.name" | default "certmanager" }}
    namespace: {{ .Values | getOrNil "certmanager.namespace" | default "certmanager" }}
  needs:
  - kube-system/{{ .Values | getOrNil "certmanager.name" | default "certmanager" }}-namespace
  values:
  - installCRDs: true
    fullnameOverride: cert-manager
    rbac:
      create: true
    ingressShim:
      defaultIssuerName: default
      defaultIssuerKind: Issuer
    serviceAccount:
      create: true
      name: ""
    prometheus:
      enabled: {{ .Values | getOrNil "prometheusoperator.enabled" | default "false" }}
      servicemonitor:
        enabled: false
    webhook:
      enabled: true
    cainjector:
      enabled: true
    resources:
      limits:
        cpu: "200m"
        memory: "256Mi"
      requests:
        cpu: "50m"
        memory: "128Mi"

- name: {{ .Values | getOrNil "certmanager.name" | default "certmanager" }}-metricsservice
  chart: {{ .Values | getOrNil "raw.chart" | default "incubator/raw" }}
  namespace: {{ .Values | getOrNil "certmanager.namespace" | default "certmanager" }}
  version: {{ .Values | getOrNil "raw.version" | default "0.2.3" }}
  condition: monitoring.enabled
  installed: true
  labels:
    chart: {{ .Values | getOrNil "certmanager.name" | default "certmanager" }}-metricsservice
    component: {{ .Values | getOrNil "certmanager.name" | default "certmanager" }}
    namespace: {{ .Values | getOrNil "certmanager.namespace" | default "certmanager" }}
  needs:
  - kube-system/{{ .Values | getOrNil "certmanager.name" | default "certmanager" }}-namespace
  values:
  - resources:
    - apiVersion: v1
      kind: Service
      metadata:
        name: {{ .Values | getOrNil "certmanager.name" | default "certmanager" }}
        labels:
          app: {{ .Values | getOrNil "certmanager.name" | default "certmanager" }}
      spec:
        type: ClusterIP
        ports:
          - protocol: TCP
            port: 9402
            targetPort: 9402
        selector:
          app.kubernetes.io/name: cert-manager
          app.kubernetes.io/instance: cert-manager

- name: {{ .Values | getOrNil "certmanager.name" | default "certmanager" }}-servicemonitor
  chart: {{ .Values | getOrNil "raw.chart" | default "incubator/raw" }}
  namespace: {{ .Values | getOrNil "certmanager.namespace" | default "certmanager" }}
  version: {{ .Values | getOrNil "raw.version" | default "0.2.3" }}
  condition: monitoring.enabled
  installed: true
  labels:
    chart: {{ .Values | getOrNil "certmanager.name" | default "certmanager" }}-servicemonitor
    component: {{ .Values | getOrNil "certmanager.name" | default "certmanager" }}
    namespace: {{ .Values | getOrNil "prometheusoperator.namespace" | default "prometheus-operator" }}
  needs:
  - {{ .Values | getOrNil "prometheusoperator.namespace" | default "prometheus-operator" }}/prometheus-operator
  values:
  - resources:
    - apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      metadata:
        name: {{ .Values | getOrNil "certmanager.name" | default "certmanager" }}
        namespace: {{ .Values | getOrNil "prometheusoperator.namespace" | default "prometheus-operator" }}
        labels:
          app: {{ .Values | getOrNil "certmanager.name" | default "certmanager" }}-servicemonitor
          release: {{ .Values | getOrNil "certmanager.name" | default "certmanager" }}-servicemonitor
          prometheus: {{ .Values.prometheus.instance }}
      spec:
        jobLabel: cert-manager
        namespaceSelector:
          matchNames:
          - {{ .Values | getOrNil "certmanager.namespace" | default "certmanager" }}
        selector:
          matchLabels:
            app: cert-manager
            release: cert-manager
        endpoints:
        - targetPort: 9402
          path: /metrics
          interval: 60s
          scrapeTimeout: 30s

- name: {{ .Values | getOrNil "certmanager.name" | default "certmanager" }}-issuers
  chart: {{ .Values | getOrNil "raw.chart" | default "incubator/raw" }}
  namespace: {{ .Values | getOrNil "certmanager.namespace" | default "certmanager" }}
  version: {{ .Values | getOrNil "raw.version" | default "0.2.3" }}
  condition: certmanager.enabled
  installed: true
  labels:
    chart: {{ .Values | getOrNil "certmanager.name" | default "certmanager" }}-issuers
    component: {{ .Values | getOrNil "certmanager.name" | default "certmanager" }}
    namespace: {{ .Values | getOrNil "certmanager.namespace" | default "certmanager" }}
  needs:
  - {{ .Values | getOrNil "certmanager.namespace" | default "certmanager" }}/{{ .Values | getOrNil "certmanager.name" | default "certmanager" }}
  - kube-system/{{ .Values | getOrNil "certmanager.name" | default "certmanager" }}-namespace
  values:
  - resources:
    - apiVersion: cert-manager.io/v1alpha3
      kind: ClusterIssuer
      metadata:
        name: {{ .Values.certmanager.issuerStaging }}
      spec:
        acme:
          server: https://acme-staging-v02.api.letsencrypt.org/directory
          email: {{ .Values.certmanager.email }}
          privateKeySecretRef:
            name: {{ .Values.certmanager.issuerStaging }}
          solvers:
            - http01:
                ingress:
                  class: {{ .Values.ingress.stage.class }}
    - apiVersion: cert-manager.io/v1alpha3
      kind: ClusterIssuer
      metadata:
        name: {{ .Values.certmanager.issuerProduction }}
      spec:
        acme:
          server: https://acme-v02.api.letsencrypt.org/directory
          email: {{ .Values.certmanager.email }}
          privateKeySecretRef:
            name: letsencrypt-prod
          solvers:
            - http01:
                ingress:
                  class: {{ .Values.ingress.external.class }}
    - apiVersion: cert-manager.io/v1alpha3
      kind: ClusterIssuer
      metadata:
        name: {{ .Values.certmanager.issuerDefault }}
      spec:
        selfSigned: {}
