---
bases:
- ../config/environments.yaml
- ../config/helmdefaults.yaml
- ../config/repositories.yaml
---

releases:
- name: csi-namespace
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.8" }}
  namespace: kube-system
  condition: csi.enabled
  installed: true
  wait: true
  labels:
    chart: csi-namespace
    component: csi
    namespace: kube-system
  values:
  - app: csi
    namespace:
      enabled: true
      name: {{ .Values | getOrNil "csi.namespace" | default "csi" }}

- name: csi
  chart: {{ .Values | getOrNil "csi.chart" | default "csidriver/secrets-store-csi-driver" }}
  version: {{ .Values | getOrNil "csi.version" | default "0.0.12" }}
  namespace: {{ .Values | getOrNil "csi.namespace" | default "csi" }}
  condition: csi.enabled
  installed: true
  missingFileHandler: Debug
  labels:
    chart: csi
    component: csi
    namespace: {{ .Values | getOrNil "csi.namespace" | default "csi" }}
  needs:
    - kube-system/csi-namespace
  values:
  - enabled: true
    image:
      repository: us.gcr.io/k8s-artifacts-prod/csi-secrets-store/driver
      tag: v0.0.12
      pullPolicy: Always
    kubeletRootDir: /var/lib/kubelet
    nodeSelector: {}
    metricsAddr: ":8080"

  # - 
  # - "../config/{{ .Environment.Name }}/csi.override.yaml"

# - name: csi-ingress
#   namespace: {{ .Values | getOrNil "csi.namespace" | default "csi" }}
#   chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
#   version: {{ .Values | getOrNil "archetype.version" | default "0.0.8" }}
#   condition: ingress.enabled
#   installed: true
#   needs:
#   - kube-system/csi-namespace
#   - {{ .Values | getOrNil "csi.namespace" | default "csi" }}/csi
#   labels:
#     chart: csi-ingress
#     component: ingress
#     namespace: {{ .Values | getOrNil "csi.namespace" | default "csi" }}
#   values:
#   - zone: internal
#     app: csi
#     dnsRoot: {{ .Values | getOrNil "dnsRoot" | default "micro.svc" }}
#     ingressClassMap:
#       internal: {{ .Values | getOrNil "ingress.internal.class" | default "internal" }}
#     ingress:
#       enabled: true
#       tlsEnabled: false
#       hosts:
#       - paths:
#         - path: "/"
#           backend:
#             serviceName: csi
#             servicePort: 80

