---
bases:
- ../config/environments.yaml
- ../config/{{ .Environment.Name }}/helmdefaults.yaml
- ../config/{{ .Environment.Name }}/repositories.yaml
---

releases:
- name: namespace-{{ .Values.rbacmanager.name }}
  chart: {{ .Values.archetype.chart }}
  version: {{ .Values.archetype.version }}
  namespace: kube-system
  condition: rbacmanager.enabled
  installed: true
  wait: true
  labels:
    chart: namespace-{{ .Values.rbacmanager.name }}
    component: {{ .Values.rbacmanager.name }}
    namespace: kube-system
  values:
  - app: {{ .Values.rbacmanager.name }}
    namespace:
      enabled: true
      name: {{ .Values.rbacmanager.namespace }}
      annotations:
        certmanager.k8s.io/disable-validation: "true"

- name: {{ .Values.rbacmanager.name }}
  chart: {{ .Values.rbacmanager.chart }}
  namespace: {{ .Values.rbacmanager.namespace }}
  version: {{ .Values.rbacmanager.version }}
  condition: rbacmanager.enabled
  installed: true
  labels:
    chart: {{ .Values.rbacmanager.name }}
    component: {{ .Values.rbacmanager.name }}
    namespace: {{ .Values.rbacmanager.namespace }}
  needs:
  - kube-system/namespace-{{ .Values.rbacmanager.name }}

- name: rolebinding-{{ .Values.rbacmanager.name }}
  chart: {{ .Values.archetype.chart }}
  namespace: {{ .Values.rbacmanager.namespace }}
  version: {{ .Values.archetype.version }}
  condition: rbacmanager.enabled
  installed: true
  labels:
    chart: rolebinding-{{ .Values.rbacmanager.name }}
    component: {{ .Values.rbacmanager.name }}
    namespace: {{ .Values.rbacmanager.namespace }}
  needs:
  - {{ .Values.rbacmanager.namespace }}/{{ .Values.rbacmanager.name }}
  values:
  - app: rolebinding-{{ .Values.rbacmanager.name }}
    clusterRole:
      enabled: true
      name: {{ .Values.rbacmanager.name }}-cluster-admin
    clusterRoleBinding:
      enabled: true
      roleName: {{ .Values.rbacmanager.name }}-cluster-admin
      serviceAccountNamespace: {{ .Values.rbacmanager.namespace }}
      serviceAccountName: default
