---
bases:
- ../config/environments.yaml
- ../config/helmdefaults.yaml
---

repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com

releases:
- name: heapster
  chart: stable/heapster
  wait: true
  installed: true
  namespace: "kube-system"
  labels:
    chart: "heapster"
    repo: "stable"
    component: "monitoring"
    namespace: "kube-system"
    vendor: "kubernetes"
