---
bases:
- ../config/environments.yaml
- ../config/helmdefaults.yaml
- ../config/repositories.yaml
---

releases:
- name: metricsserver
  chart: {{ .Values | getOrNil "metricsserver.chart" | default "stable/metrics-server" }}
  namespace: kube-system
  version: {{ .Values | getOrNil "metricsserver.version" | default "2.11.1" }}
  wait: true
  condition: metricsserver.enabled
  installed: true
  missingFileHandler: Debug
  labels:
    chart: metricsserver
    component: metricsserver
    namespace: kube-system
  values:
  - args:
    - '--kubelet-insecure-tls'
    - '--kubelet-preferred-address-types=InternalIP'
  - "../config/{{ .Environment.Name }}/metricsserver.override.yaml"