---
bases:
- ../config/environments.yaml
- ../config/helmdefaults.yaml
- ../config/repositories.yaml
---

## Kube-Fledged
# Source: https://github.com/senthilrch/kube-fledged
releases:
- name: namespace-kubefledged
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.8" }}
  namespace: kube-system
  condition: kubefledged.enabled
  installed: true
  wait: true
  labels:
    chart: namespace-kubefledged
    component: kubefledged
    namespace: kube-system
  values:
  - app: kubefledged
    namespace:
      enabled: true
      name: {{ .Values | getOrNil "kubefledged.namespace" | default "kubefledged" }}

# Install kube-fledged
- name: kubefledged
  chart: {{ .Values | getOrNil "kubefledged.chart" | default "kubefledged/kubefledged" }}
  version: {{ .Values | getOrNil "kubefledged.version" | default "0.7.0" }}
  namespace: {{ .Values | getOrNil "kubefledged.namespace" | default "kubefledged" }}
  condition: kubefledged.enabled
  installed: true
  missingFileHandler: Debug
  labels:
    chart: kubefledged
    component: kubefledged
    namespace: {{ .Values | getOrNil "kubefledged.namespace" | default "kubefledged" }}
  needs:
    - kube-system/namespace-kubefledged
  values:
  - kubefledgedNameSpace: {{ .Values | getOrNil "kubefledged.namespace" | default "kubefledged" }}
  - "../config/{{ .Environment.Name }}/kubefledged.override.yaml"

# ## Create a default image cache
# - name: kubefledged-imagecache
#   chart: {{ .Values | getOrNil "raw.chart" | default "incubator/raw" }}
#   version: {{ .Values | getOrNil "raw.version" | default "0.2.3" }}
#   namespace: {{ .Values | getOrNil "kubefledged.namespace" | default "kubefledged" }}
#   condition: kubefledged.enabled
#   installed: true
#   needs:
#   - {{ .Values | getOrNil "kubefledged.namespace" | default "kubefledged" }}/kubefledged
#   values:
#   - resources:
#     - apiVersion: fledged.k8s.io/v1alpha1
#       kind: ImageCache
#       metadata:
#         name: baseclusterservices
#       spec:
#         cacheSpec:
#         # Specifies a list of images (nginx and tomcat:10.0.0) with no node selector, hence these images will be cached in all the nodes in the cluster
#         - images:
#           - quay.io/jetstack/cert-manager-controller:v0.15.0
#         # # Specifies a list of images (redis:latest and postgres:12.3) with a node selector, hence these images will be cached only on the nodes selected by the node selector
#         # - images:
#         #   - redis:latest
#         #   - postgres:12.3
#         #   nodeSelector:
#         #     tier: backend
#         # Specifies a list of image pull secrets to pull images from private repositories into the cache
#         # imagePullSecrets:
#         # - name: myregistrykey