---
bases:
- ../config/environments.yaml
- ../config/helmdefaults.yaml
- ../config/{{ .Environment.Name }}/repositories.yaml
---

## Prometheus Operator
# site: https://github.com/helm/charts/blob/master/stable/prometheus-operator/values.yaml
releases:
- name: {{ .Values | getOrNil "prometheusoperator.name" | default "po" }}-namespace
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.1" }}
  namespace: kube-system
  condition: prometheusoperator.enabled
  installed: true
  wait: true
  labels:
    chart: {{ .Values | getOrNil "prometheusoperator.name" | default "po" }}-namespace
    component: {{ .Values | getOrNil "prometheusoperator.name" | default "po" }}
    namespace: kube-system
  values:
  - app: {{ .Values | getOrNil "prometheusoperator.name" | default "po" }}
    namespace:
      enabled: true
      name: {{ .Values | getOrNil "prometheusoperator.namespace" | default "prometheus-operator" }}

- name: {{ .Values | getOrNil "prometheusoperator.name" | default "po" }}
  chart: {{ .Values | getOrNil "prometheusoperator.chart" | default "stable/prometheus-operator" }}
  version: {{ .Values | getOrNil "prometheusoperator.version" | default "8.13.8" }}
  namespace: {{ .Values | getOrNil "prometheusoperator.namespace" | default "prometheus-operator" }}
  condition: prometheusoperator.enabled
  installed: true
  labels:
    chart: {{ .Values | getOrNil "prometheusoperator.name" | default "po" }}
    component: {{ .Values | getOrNil "prometheusoperator.name" | default "po" }}
    namespace: {{ .Values | getOrNil "prometheusoperator.namespace" | default "prometheus-operator" }}
  needs:
  - kube-system/{{ .Values | getOrNil "prometheusoperator.name" | default "po" }}-namespace
  values:
  - fullnameOverride: {{ .Values | getOrNil "prometheusoperator.name" | default "po" }}
    alertmanager:
      alertmanagerSpec:
        externalUrl: http://alertmanager.{{ .Values | getOrNil "ingress.internal.zone" | default "int" }}.{{ .Values | getOrNil "dnsRoot" | default "micro.svc" }}
    prometheus:
      prometheusSpec:
        externalUrl: http://prometheus.{{ .Values | getOrNil "ingress.internal.zone" | default "int" }}.{{ .Values | getOrNil "dnsRoot" | default "micro.svc" }}

- name: {{ .Values | getOrNil "prometheusoperator.name" | default "po" }}-grafana-ingress
  namespace: {{ .Values | getOrNil "prometheusoperator.namespace" | default "prometheus-operator" }}
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.1" }}
  condition: ingress.enabled
  installed: true
  needs:
  - kube-system/{{ .Values | getOrNil "prometheusoperator.name" | default "po" }}-namespace
  - {{ .Values | getOrNil "prometheusoperator.namespace" | default "prometheus-operator" }}/{{ .Values | getOrNil "prometheusoperator.name" | default "po" }}
  labels:
    chart: {{ .Values | getOrNil "prometheusoperator.name" | default "po" }}-grafana-ingress
    component: {{ .Values | getOrNil "prometheusoperator.name" | default "po" }}
    namespace: {{ .Values | getOrNil "prometheusoperator.namespace" | default "prometheus-operator" }}
  values:
  - app: grafana
    dnsRoot: {{ .Values | getOrNil "dnsRoot" | default "micro.svc" }}
    zone: {{ .Values | getOrNil "prometheusoperator.zone" | default "internal" }}
    ingressClassMap:
      internal: {{ .Values | getOrNil "ingress.internal.class" | default "internal" }}
      external: {{ .Values | getOrNil "ingress.external.class" | default "external" }}
      stage: {{ .Values | getOrNil "ingress.stage.class" | default "stage" }}
    zoneMap:
      internal: {{ .Values | getOrNil "ingress.internal.zone" | default "int" }}
      external: {{ .Values | getOrNil "ingress.external.zone" | default "ext" }}
      staging: {{ .Values | getOrNil "ingress.stage.zone" | default "stage" }}
      default: ""
    ingress:
      enabled: true
      tlsEnabled: true
      hosts:
      - secretName: {{ .Values | getOrNil "prometheusoperator.name" | default "po" }}-grafana-ingress
        config:
          http:
            paths:
            - path: "/"
              backend:
                serviceName: {{ .Values | getOrNil "prometheusoperator.name" | default "po" }}-grafana
                servicePort: 80

- name: {{ .Values | getOrNil "prometheusoperator.name" | default "po" }}-prometheus-ingress
  namespace: {{ .Values | getOrNil "prometheusoperator.namespace" | default "prometheus-operator" }}
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.1" }}
  condition: ingress.enabled
  installed: true
  needs:
  - kube-system/{{ .Values | getOrNil "prometheusoperator.name" | default "po" }}-namespace
  - {{ .Values | getOrNil "prometheusoperator.namespace" | default "prometheus-operator" }}/{{ .Values | getOrNil "prometheusoperator.name" | default "po" }}
  labels:
    chart: {{ .Values | getOrNil "prometheusoperator.name" | default "po" }}-prometheus-ingress
    component: {{ .Values | getOrNil "prometheusoperator.name" | default "po" }}
    namespace: {{ .Values | getOrNil "prometheusoperator.namespace" | default "prometheus-operator" }}
  values:
  - app: prometheus
    dnsRoot: {{ .Values | getOrNil "dnsRoot" | default "micro.svc" }}
    zone: {{ .Values | getOrNil "prometheusoperator.zone" | default "internal" }}
    ingressClassMap:
      internal: {{ .Values | getOrNil "ingress.internal.class" | default "internal" }}
      external: {{ .Values | getOrNil "ingress.external.class" | default "external" }}
      stage: {{ .Values | getOrNil "ingress.stage.class" | default "stage" }}
    zoneMap:
      internal: {{ .Values | getOrNil "ingress.internal.zone" | default "int" }}
      external: {{ .Values | getOrNil "ingress.external.zone" | default "ext" }}
      staging: {{ .Values | getOrNil "ingress.stage.zone" | default "stage" }}
      default: ""
    ingress:
      enabled: true
      tlsEnabled: true
      hosts:
      - secretName: {{ .Values | getOrNil "prometheusoperator.name" | default "po" }}-prometheus-ingress
        config:
          http:
            paths:
            - path: "/"
              backend:
                serviceName: {{ .Values | getOrNil "prometheusoperator.name" | default "po" }}-prometh-prometheus
                servicePort: 9090

- name: {{ .Values | getOrNil "prometheusoperator.name" | default "po" }}-alertmanager-ingress
  namespace: {{ .Values | getOrNil "prometheusoperator.namespace" | default "prometheus-operator" }}
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.1" }}
  condition: ingress.enabled
  installed: true
  needs:
  - kube-system/{{ .Values | getOrNil "prometheusoperator.name" | default "po" }}-namespace
  - {{ .Values | getOrNil "prometheusoperator.namespace" | default "prometheus-operator" }}/{{ .Values | getOrNil "prometheusoperator.name" | default "po" }}
  labels:
    chart: {{ .Values | getOrNil "prometheusoperator.name" | default "po" }}-alertmanager-ingress
    component: {{ .Values | getOrNil "prometheusoperator.name" | default "po" }}
    namespace: {{ .Values | getOrNil "prometheusoperator.namespace" | default "prometheus-operator" }}
  values:
  - app: alertmanager
    dnsRoot: {{ .Values | getOrNil "dnsRoot" | default "micro.svc" }}
    zone: {{ .Values | getOrNil "prometheusoperator.zone" | default "internal" }}
    ingressClassMap:
      internal: {{ .Values | getOrNil "ingress.internal.class" | default "internal" }}
      external: {{ .Values | getOrNil "ingress.external.class" | default "external" }}
      stage: {{ .Values | getOrNil "ingress.stage.class" | default "stage" }}
    zoneMap:
      internal: {{ .Values | getOrNil "ingress.internal.zone" | default "int" }}
      external: {{ .Values | getOrNil "ingress.external.zone" | default "ext" }}
      staging: {{ .Values | getOrNil "ingress.stage.zone" | default "stage" }}
      default: ""
    ingress:
      enabled: true
      tlsEnabled: true
      hosts:
      - secretName: {{ .Values | getOrNil "prometheusoperator.name" | default "po" }}-alertmanager-ingress
        config:
          http:
            paths:
            - path: "/"
              backend:
                serviceName: {{ .Values | getOrNil "prometheusoperator.name" | default "po" }}-prometh-alertmanager
                servicePort: 9093