---
bases:
- ../config/environments.yaml
- ../config/{{ .Environment.Name }}/helmdefaults.yaml
- ../config/{{ .Environment.Name }}/repositories.yaml
---

releases:
- name: {{ .Values | getOrNil "homeassistant.name" | default "homeassistant" }}-namespace
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.1" }}
  namespace: kube-system
  condition: homeassistant.enabled
  installed: true
  wait: true
  labels:
    chart: {{ .Values | getOrNil "homeassistant.name" | default "homeassistant" }}-namespace
    component: {{ .Values | getOrNil "homeassistant.name" | default "homeassistant" }}
    namespace: kube-system
  values:
  - app: {{ .Values | getOrNil "homeassistant.name" | default "homeassistant" }}
    namespace:
      enabled: true
      name: {{ .Values | getOrNil "homeassistant.namespace" | default "homeassistant" }}

- name: {{ .Values | getOrNil "homeassistant.name" | default "homeassistant" }}
  chart: {{ .Values | getOrNil "homeassistant.chart" | default "stable/home-assistant" }}
  version: {{ .Values | getOrNil "homeassistant.version" | default "0.13.3" }}
  namespace: {{ .Values | getOrNil "homeassistant.namespace" | default "homeassistant" }}
  condition: homeassistant.enabled
  installed: true
  labels:
    chart: {{ .Values | getOrNil "homeassistant.name" | default "homeassistant" }}
    component: {{ .Values | getOrNil "homeassistant.name" | default "homeassistant" }}
    namespace: {{ .Values | getOrNil "homeassistant.namespace" | default "homeassistant" }}
  needs:
    - kube-system/{{ .Values | getOrNil "homeassistant.name" | default "homeassistant" }}-namespace
  values:
  - hostNetwork: true
    vscode:
      enabled: true

# - name: {{ .Values | getOrNil "homeassistant.name" | default "homeassistant" }}-ingress
#   namespace: {{ .Values | getOrNil "homeassistant.namespace" | default "homeassistant" }}
#   chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
#   version: {{ .Values | getOrNil "archetype.version" | default "0.0.1" }}
#   condition: ingress.enabled
#   installed: true
#   needs:
#   - kube-system/{{ .Values | getOrNil "homeassistant.name" | default "homeassistant" }}-namespace
#   - {{ .Values | getOrNil "homeassistant.namespace" | default "homeassistant" }}/{{ .Values | getOrNil "homeassistant.name" | default "homeassistant" }}
#   labels:
#     chart: {{ .Values | getOrNil "homeassistant.name" | default "homeassistant" }}-ingress
#     component: {{ .Values | getOrNil "homeassistant.name" | default "homeassistant" }}
#     namespace: {{ .Values | getOrNil "homeassistant.namespace" | default "homeassistant" }}
#   values:
#   - zone: internal
#     app: dashboard
#     ingressClassMap:
#       internal: {{ .Values | getOrNil "ingress.internal.class" | default "internal" }}
#       external: {{ .Values | getOrNil "ingress.external.class" | default "external" }}
#       stage: {{ .Values | getOrNil "ingress.stage.class" | default "stage" }}
#     ingress:
#       enabled: true
#       tlsEnabled: true
#       hosts:
#       - secretName: ingress-homeassistant-dashboard
#         config:
#           http:
#             paths:
#             - path: "/"
#               backend:
#                 serviceName: homeassistant-homeassistant-ui
#                 servicePort: 80
