---
bases:
- ../config/environments.yaml
- ../config/{{ .Environment.Name }}/helmdefaults.yaml
- ../config/{{ .Environment.Name }}/repositories.yaml
---

releases:
- name: {{ .Values.metricsserver.name }}
  chart: {{ .Values.metricsserver.chart }}
  namespace: kube-system
  version: {{ .Values.metricsserver.version }}
  wait: true
  condition: metricsserver.enabled
  installed: true
  labels:
    chart: {{ .Values.metricsserver.name }}
    component: {{ .Values.metricsserver.name }}
    namespace: kube-system
  values:
  - args:
    - '--kubelet-insecure-tls'
    - '--kubelet-preferred-address-types=InternalIP'
