---
bases:
- ../config/environments.yaml
- ../config/{{ .Environment.Name }}/helmdefaults.yaml
- ../config/{{ .Environment.Name }}/repositories.yaml
---

releases:
- name: {{ .Values | getOrNil "vault.name" | default "vault" }}-namespace
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.1" }}
  namespace: kube-system
  condition: vault.enabled
  installed: true
  wait: true
  labels:
    chart: {{ .Values | getOrNil "vault.name" | default "vault" }}-namespace
    component: {{ .Values | getOrNil "vault.name" | default "vault" }}
    namespace: kube-system
  values:
  - app: {{ .Values | getOrNil "vault.name" | default "vault" }}
    namespace:
      enabled: true
      name: {{ .Values | getOrNil "vault.namespace" | default "vault" }}

- name: {{ .Values | getOrNil "vault.name" | default "vault" }}
  chart: {{ .Values | getOrNil "vault.chart" | default "vault/vault" }}
  version: {{ .Values | getOrNil "vault.version" | default "0.5.0" }}
  namespace: {{ .Values | getOrNil "vault.namespace" | default "vault" }}
  condition: vault.enabled
  installed: true
  labels:
    chart: {{ .Values | getOrNil "vault.name" | default "vault" }}
    component: {{ .Values | getOrNil "vault.name" | default "vault" }}
    namespace: {{ .Values | getOrNil "vault.namespace" | default "vault" }}
  needs:
    - kube-system/{{ .Values | getOrNil "vault.name" | default "vault" }}-namespace
  values:
  - server:
      # affinity: ""
      ha:
        enabled: true
      service: 
        type: LoadBalancer
      dev:
        enabled: true
      dataStorage:
        enabled: true
        size: 2Gi
    ui:
      enabled: true

- name: {{ .Values | getOrNil "vault.name" | default "vault" }}-ingress
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.1" }}
  namespace: {{ .Values | getOrNil "vault.namespace" | default "vault" }}
  condition: ingress.enabled
  installed: true
  needs:
  - kube-system/{{ .Values | getOrNil "vault.name" | default "vault" }}-namespace
  - {{ .Values | getOrNil "vault.namespace" | default "vault" }}/{{ .Values | getOrNil "vault.name" | default "vault" }}
  labels:
    chart: {{ .Values | getOrNil "vault.name" | default "vault" }}-ingress
    component: ingress
    namespace: {{ .Values | getOrNil "vault.namespace" | default "vault" }}
  values:
  - zone: internal
    app: {{ .Values | getOrNil "vault.name" | default "vault" }}
    ingressClassMap:
      internal: {{ .Values | getOrNil "ingress.internal.class" | default "internal" }}
    ingress:
      enabled: true
      tlsEnabled: true
      hosts:
      # - name: vault.{{ .Values | getOrNil "ingress.internal.zone" | default "int.micro.svc" }}
      - secretName: ingress-vault-dashboard
        config:
          http:
            paths:
            - path: "/"
              backend:
                serviceName: vault-ui
                servicePort: 8200

## Role binding needed to do vault auth
- name: {{ .Values | getOrNil "vault.name" | default "vault" }}-rolebinding
  chart: {{ .Values | getOrNil "raw.chart" | default "incubator/raw" }}
  version: {{ .Values | getOrNil "raw.version" | default "0.2.3" }}
  namespace: {{ .Values | getOrNil "vault.namespace" | default "vault" }}
  condition: vault.enabled
  installed: true
  needs:
  - {{ .Values | getOrNil "vault.namespace" | default "vault" }}/{{ .Values | getOrNil "vault.name" | default "vault" }}
  values:
  - resources:
    - apiVersion: rbacmanager.reactiveops.io/v1beta1
      kind: RBACDefinition
      metadata:
        name: rolebinding-{{ .Values | getOrNil "vault.name" | default "vault" }}
      rbacBindings:
      - name: example-service-account
        subjects:
          - kind: ServiceAccount
            name: vault
            namespace: {{ .Values | getOrNil "vault.namespace" | default "vault" }}
        clusterRoleBindings:
          - clusterRole: system:auth-delegator