---
bases:
- ../config/environments.yaml
- ../config/{{ .Environment.Name }}/helmdefaults.yaml
- ../config/{{ .Environment.Name }}/repositories.yaml
---

releases:
- name: {{ .Values.consul.name }}-namespace
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.1" }}
  namespace: kube-system
  condition: consul.enabled
  installed: true
  wait: true
  labels:
    chart: {{ .Values.consul.name }}-namespace
    component: {{ .Values.consul.name }}
    namespace: kube-system
  values:
  - app: {{ .Values.consul.name }}
    namespace:
      enabled: true
      name: {{ .Values.consul.namespace }}

## consul Deployment
- name: {{ .Values.consul.name }}
  chart: {{ .Values.consul.chart }}
  version: {{ .Values.consul.version }}
  namespace: {{ .Values.consul.namespace }}
  condition: consul.enabled
  installed: true
  labels:
    chart: {{ .Values.consul.name }}
    component: {{ .Values.consul.name }}
    namespace: {{ .Values.consul.namespace }}
  needs:
    - kube-system/{{ .Values.consul.name }}-namespace
  values:
  - dns:
      enabled: false
    client:
      enabled: true
    server:
      replicas: 1
      bootstrapExpect: 1
      disruptionBudget:
        maxUnavailable: 0
      storage: 2Gi
    ui:
      enabled: true
    service:
      type: LoadBalancer
    consulNamespaces:
      consulDestinationNamespace: kube
      mirroringK8S: false

- name: {{ .Values.consul.name }}-ingress
  namespace: {{ .Values.consul.namespace }}
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.1" }}
  condition: consul.enabled
  installed: true
  needs:
  - kube-system/{{ .Values.consul.name }}-namespace
  labels:
    chart: {{ .Values.consul.name }}-ingress
    component: ingress
    namespace: {{ .Values.consul.namespace }}
  values:
  - zone: internal
    app: consul-dashboard
    ingressClassMap:
      internal: {{ .Values | getOrNil "ingress.internal.class" | default "internal" }}
    ingress:
      enabled: true
      tlsEnabled: true
      hosts:
      - name: consul.{{ .Values | getOrNil "ingress.internal.zone" | default "int.micro.svc" }}
        secretName: ingress-consul-dashboard
        config:
          http:
            paths:
            - path: "/"
              backend:
                serviceName: consul-consul-ui
                servicePort: 80
