environments:
  default:
    values:
    - ../config/default/values.yaml
    - prometheusoperator:
        enabled: false
  monitoring:
    values:
    - ../config/default/values.yaml
  istio:
    values:
    - ../config/default/values.yaml
    - prometheusoperator:
        enabled: false
    - traefik:
        enabled: false
  homeassist:
    values:
    - ../config/default/values.yaml
    - ingress:
        internal:
          subnet: "192.168.1.10-192.168.1.20"
          ip: "192.168.1.10"
    - nfsstorage:
        server: "10.20.20.1"
        path: /nfs-kube
  vaultha:
    values:
    - ../config/default/values.yaml
    - prometheusoperator:
        enabled: false
    - vault:
        dev: false
        ha: true