## Possible environments. default would be a locally hosted kubernetes instance
environments:
  default:
    values:
      - ../config/environment.default.yaml
  istio:
    values:
      - ../config/environment.istio.yaml