environments:
  default:
    values:
    - ../config/default/values.yaml
    - monitoring:
        enabled: false
  istio:
    values:
    - ../config/istio/values.yaml
    - monitoring:
        enabled: false
    - traefik:
        enabled: false