environments:
  default:
    missingFileHandler: Debug
    secrets:
    - ../config/{{ .Environment.Name }}/secrets.yaml
    values:
    - ../config/{{ .Environment.Name }}/values.yaml
    - prometheusoperator:
        enabled: false
  istio:
    missingFileHandler: Debug
    secrets:
    - ../config/{{ .Environment.Name }}/secrets.yaml
    values:
    - ../config/default/values.yaml
    - ../config/{{ .Environment.Name }}/values.yaml
    - prometheusoperator:
        enabled: false
    - ingress:
        internal:
          namespace: istio-system
    - traefik:
        enabled: false
  monitoring:
    missingFileHandler: Debug
    secrets:
    - ../config/{{ .Environment.Name }}/secrets.yaml
    values:
    - ../config/default/values.yaml
    - ../config/{{ .Environment.Name }}/values.yaml
  homeassist:
    missingFileHandler: Debug
    secrets:
    - ../config/{{ .Environment.Name }}/secrets.yaml
    values:
    - ../config/default/values.yaml
    - ../config/{{ .Environment.Name }}/values.yaml
    - ingress:
        internal:
          subnet: "192.168.1.10-192.168.1.20"
          ip: "192.168.1.10"
    - nfsstorage:
        server: "10.20.20.1"
        path: /nfs-kube
  vaultha:
    missingFileHandler: Debug
    secrets:
    - ../config/{{ .Environment.Name }}/secrets.yaml
    values:
    - ../config/default/values.yaml
    - ../config/{{ .Environment.Name }}/values.yaml
    - prometheusoperator:
        enabled: false
    - vault:
        dev: false
        ha: true
  vaultoverride:
    missingFileHandler: Debug
    secrets:
    - ../config/{{ .Environment.Name }}/secrets.yaml
    values:
    - ../config/default/values.yaml
    - ../config/{{ .Environment.Name }}/values.yaml
    - prometheusoperator:
        enabled: false
    - vault:
        dev: false
        ha: true
  testing:
    missingFileHandler: Debug
    secrets:
    - ../config/{{ .Environment.Name }}/secrets.yaml
    values:
    - ../config/default/values.yaml
    - prometheusoperator:
        enabled: false
    - archetype:
        version: "0.0.10"
        chart: archetype-incubator/archetype
  gitlab:
    missingFileHandler: Debug
    secrets:
    - ../config/{{ .Environment.Name }}/secrets.yaml
    values:
    - ../config/default/values.yaml
    - ../config/{{ .Environment.Name }}/values.yaml
    - prometheusoperator:
        enabled: false
