repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: incubator
  url: https://kubernetes-charts-incubator.storage.googleapis.com
- name: archetype
  url: https://zloeber.github.io/archetype-chart
- name: descendant
  url: https://zloeber.github.io/descendant-chart 
- name: containous
  url: https://containous.github.io/traefik-helm-chart
- name: jetstack
  url: https://charts.jetstack.io
- name: hashicorp
  url: https://helm.releases.hashicorp.com
- name: reactiveops-stable
  url: https://charts.reactiveops.com/stable
- name: rancher
  url: https://releases.rancher.com/server-charts/latest
- name: argocd
  url: https://argoproj.github.io/argo-helm
- name: kubefledged
  url: git+https://github.com/senthilrch/kube-fledged@/deploy/kubefledged-operator/helm-charts/kubefledged
- name: istiooperator
  url: git+https://github.com/istio/istio@/manifests/charts/istio-operator
- name: archetype-incubator
  url: git+https://github.com/zloeber/archetype-chart@/
- name: descendant-incubator
  url: git+https://github.com/zloeber/descendant-chart@/
- name: gitlab
  url: https://charts.gitlab.io
- name: appscode
  url: https://charts.appscode.com/stable/
- name: devspace
  url: https://charts.devspace.sh/
- name: csidriver
  url: https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/master/charts
- name: lifen
  url: https://honestica.github.io/lifen-charts
- name: deislabs
  url: https://deislabs.github.io/akri/
- name: k8s-at-home
  url: https://k8s-at-home.com/charts/
