repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: incubator
  url: https://kubernetes-charts-incubator.storage.googleapis.com
- name: zloeber
  url: git+https://github.com/zloeber/archetype-chart@/
- name: containous
  url: https://containous.github.io/traefik-helm-chart
- name: jetstack
  url: https://charts.jetstack.io
- name: hashicorp
  url: https://helm.releases.hashicorp.com
- name: reactiveops-stable
  url: https://charts.reactiveops.com/stable
- name: rancher
  url: https://releases.rancher.com/server-charts/latest
- name: argocd
  url: https://argoproj.github.io/argo-helm
- name: kubefledged
  url: git+https://github.com/senthilrch/kube-fledged@/deploy/kubefledged-operator/helm-charts/kubefledged
- name: istiooperator
  url: git+https://github.com/istio/istio@/manifests/charts/istio-operator
