repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: incubator
  url: https://kubernetes-charts-incubator.storage.googleapis.com
- name: zloeber
  url: git+https://github.com/zloeber/archetype-chart@/
- name: jetstack
  url: https://charts.jetstack.io
- name: reactiveops-stable
  url: https://charts.reactiveops.com/stable
