cloud: local
dnsRoot: loeber.live
init:
  enabled: true
  namespace: cluster-init  
ingress:
  enabled: true
  dashboard: true
  type: default
  internal:
    namespace: ingress-int
    class: internal
    zone: int
    subnet: "192.168.1.0/24"
    ip: ""
  external:
    namespace: ingress-ext
    class: external
    zone: ext
    ip: ""
  stage:
    namespace: ingress-stage
    class: stage
    zone: stage
    ip: ""
archetype:
  version: "0.0.9"
  chart: archetype/archetype
descendant:
  enabled: true
  version: "0.0.2"
  chart: descendant-incubator/descendant-service
raw:
  version: "0.2.3"
  chart: incubator/raw
traefik:
  enabled: true
  version: "9.1.1"
  chart: containous/traefik
  dashboard: true
  zone: internal
certmanager:
  enabled: true
  version: "0.15.1"
  chart: jetstack/cert-manager
  namespace: cert-manager
  serviceaccountname: ""
  email: someuser@realdomain.com
  issuerDefault: default
  issuerStaging: letsencrypt-staging
  issuerProduction: letsencrypt-prod
  zone: internal
metricsserver:
  enabled: true
  version: "2.11.1"
  chart: stable/metrics-server
  zone: internal
rbacmanager:
  enabled: true
  version: "1.5.4"
  chart: reactiveops-stable/rbac-manager
  namespace: rbacmanager
  zone: internal
prometheusoperator:
  name: po
  enabled: true
  version: "8.13.8"
  chart: stable/prometheus-operator
  namespace: prometheus-operator
  zone: internal
nfsstorage:
  enabled: true
  version: "1.2.8"
  chart: stable/nfs-client-provisioner
  namespace: nfs-storage
  server: 10.20.20.1
  path: /nfs-kube
  defaultClass: 
homeassistant:
  enabled: true
  version: "2.5.2"
  chart: k8s-at-home/home-assistant
  namespace: home-assistant
  zone: internal
gitlab:
  enabled: true
  version: "4.2.2"
  chart: gitlab/gitlab
  namespace: gitlab
  zone: internal
  gitlabVersion: "13.2.2"
akri:
  enabled: true
  version: "0.0.36"
  chart: deislabs/akri
  namespace: akri
  zone: internal