cloud: local
dnsRoot: home.local
archetype:
  version: "0.0.2"
  chart: zloeber/archetype
raw:
  version: "0.2.3"
  chart: incubator/raw
ingress:
  enabled: true
  dashboard: true
  type: default
  internal:
    namespace: ingress-int
    class: internal
    zone: int
    ip: "192.168.1.10"
  external:
    namespace: ingress-ext
    class: external
    zone: ext
    ip: ""
  stage:
    namespace: ingress-stage
    class: stage
    zone: stage
    ip: ""
traefik:
  name: traefik
  enabled: true
  version: "8.2.1"
  chart: traefik/traefik
  dashboard: true
  zone: internal
certmanager:
  name: certmanager
  enabled: true
  version: "0.15.0"
  chart: jetstack/cert-manager
  namespace: cert-manager
  serviceaccountname: ""
  email: someuser@realdomain.com
  issuerDefault: default
  issuerStaging: letsencrypt-staging
  issuerProduction: letsencrypt-prod
  zone: internal
prometheus:
  instance: kube-prometheus
metricsserver:
  name: metricsserver
  enabled: true
  version: "2.11.1"
  chart: stable/metrics-server
  zone: internal
rbacmanager:
  name: rbacmanager
  enabled: true
  version: "1.5.4"
  chart: reactiveops-stable/rbac-manager
  namespace: rbacmanager
  zone: internal
prometheusoperator:
  name: prometheusoperator
  enabled: true
  version: "8.13.8"
  chart: stable/prometheus-operator
  namespace: prometheus-operator
  zone: internal
nfsstorage:
  name: nfsstorage
  enabled: true
  version: "1.2.8"
  chart: stable/nfs-client-provisioner
  namespace: nfs-storage
  server: ""
  path: /nfs-kube
homeassistant:
  name: homeassistant
  enabled: true
  version: "0.13.3"
  chart: stable/home-assistant
  namespace: home-assistant
  zone: internal
  
