helmDefaults:
  tillerless: true
  tillerNamespace: platform
  atomic: false
  verify: false
  wait: false
  timeout: 600
  recreatePods: false
  force: true


releases:
## Deploy nextgen configmap for dev-policy
- name: confmap-inventory-dev-policy
  namespace: "nextgen-dev-policy"
  chart: {{ env "ARCHTYPE_CHART" | default "../charts/archtype" }}
  version: 0.0.1
  labels:
    chart: "nextgen-dev-policy"
    component: "nextgen-configmap"
    namespace: "nextgen-dev-policy"
  values:
  - project:
      app: "policy"
      team: "inv"
      target: {{ env "TARGET" | default "cicd" }}
      client: "mcd"
      workload: "dev"
      engine: "nextgen"
    nextgenconfigmaps:
      enabled: true
      jdbc:
        password: "SimplePassword"
      storageaccount:
        key: "your_key"
      checkpoint:
        account:
          key: "some_random_key"
        container:
          name: "checkpoints"
# - name: servicemonitor-sparkstream-execs
#   namespace: {{ env "STACK_MONITORING_NAMESPACE" | default "monitoring" }}
#   version: 0.0.1
#   chart: {{ env "ARCHTYPE_CHART" | default "../charts/archtype" }}
#   labels:
#     chart: "servicemonitor-sparkstream-execs"
#     component: "servicemonitor"
#     namespace: {{ env "STACK_MONITORING_NAMESPACE" | default "monitoring" }}
#   values:
#   - project:
#       app: "spark"
#       team: "operations"
#       buildid: "latest"
#       target: {{ env "TARGET" | default "cicd" }}
#       client: {{ env "CLIENT" | default "client1" }}
#       workload: "servicemonitor"
#       engine: "monitoring"
#       project: "nextgen"
#     serviceMonitors:
#     - spark-stream:
#         enabled: true
#         endpoints:
#         - interval: 30s
#           port: metrics
#         namespaceSelector:
#           matchNames:
#           - "inventory-dev-stream"
#         selector:
#           matchLabels:
#             spark-role: executor