---
bases:
- ../config/environments.yaml
- ../config/helmdefaults.yaml
- ../config/repositories.yaml
---

## withingress namespace
releases:
- name: withingress-namespace
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.8" }}
  namespace: kube-system
  condition: withingress.enabled
  installed: true
  wait: true
  labels:
    chart: withingress-namespace
    component: withingress
    namespace: kube-system
  values:
  - app: withingress
    namespace:
      enabled: true
      name: {{ .Values | getOrNil "withingress.namespace" | default "withingress" }}

## withingress chart deployment
- name: withingress
  chart: {{ .Values | getOrNil "withingress.chart" | default "withingress/withingress" }}
  version: {{ .Values | getOrNil "withingress.version" | default "0.21.0" }}
  namespace: {{ .Values | getOrNil "withingress.namespace" | default "withingress" }}
  condition: withingress.enabled
  installed: true
  missingFileHandler: Debug
  labels:
    chart: withingress
    component: withingress
    namespace: {{ .Values | getOrNil "withingress.namespace" | default "withingress" }}
  needs:
    - kube-system/withingress-namespace
  values:
  - value1:
      enabled: false
  - "../config/{{ .Environment.Name }}/withingress.override.yaml"

## withingress ingress deployment
- name: withingress-ingress
  namespace: {{ .Values | getOrNil "withingress.namespace" | default "withingress" }}
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.8" }}
  condition: ingress.enabled
  installed: true
  needs:
  - kube-system/withingress-namespace
  - {{ .Values | getOrNil "withingress.namespace" | default "withingress" }}/withingress
  labels:
    chart: withingress-ingress
    component: ingress
    namespace: {{ .Values | getOrNil "withingress.namespace" | default "withingress" }}
  values:
  - zone: internal
    app: withingress
    dnsRoot: {{ .Values | getOrNil "dnsRoot" | default "micro.svc" }}
    ingressClassMap:
      internal: {{ .Values | getOrNil "ingress.internal.class" | default "internal" }}
    ingress:
      enabled: true
      tlsEnabled: true
      hosts:
      - secretName: withingress-ingress
        paths:
        - path: "/"
          backend:
            serviceName: withingress-service
            servicePort: 80