---
bases:
- ../config/environments.yaml
- ../config/helmdefaults.yaml
- ../config/repositories.yaml
---

## Simple Template helmfile
# Replace 'simple' with your service/chart name
releases:
- name: simple-namespace
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.2" }}
  namespace: kube-system
  condition: simple.enabled
  installed: true
  wait: true
  labels:
    chart: simple-namespace
    component: simple
    namespace: kube-system
  values:
  - app: simple
    namespace:
      enabled: true
      name: {{ .Values | getOrNil "simple.namespace" | default "simple" }}

- name: simple
  chart: {{ .Values | getOrNil "simple.chart" | default "simple/simple" }}
  version: {{ .Values | getOrNil "simple.version" | default "0.0.1" }}
  namespace: {{ .Values | getOrNil "simple.namespace" | default "simple" }}
  condition: simple.enabled
  installed: true
  missingFileHandler: Debug
  labels:
    chart: simple
    component: simple
    namespace: {{ .Values | getOrNil "simple.namespace" | default "simple" }}
  needs:
    - kube-system/simple-namespace
  values:
  - somevalues:
      somevalue1: value
  - "../config/{{ .Environment.Name }}/simple.override.yaml"

- name: simple-ingress
  namespace: {{ .Values | getOrNil "simple.namespace" | default "simple" }}
  chart: {{ .Values | getOrNil "archetype.chart" | default "zloeber/archetype" }}
  version: {{ .Values | getOrNil "archetype.version" | default "0.0.2" }}
  condition: ingress.enabled
  installed: true
  needs:
  - kube-system/simple-namespace
  - {{ .Values | getOrNil "simple.namespace" | default "simple" }}/simple
  labels:
    chart: simple-ingress
    component: simple
    namespace: {{ .Values | getOrNil "simple.namespace" | default "simple" }}
  values:
  - zone: {{ .Values | getOrNil "simple.zone" | default "internal" }}
    app: dashboard
    ingressClassMap:
      internal: {{ .Values | getOrNil "ingress.internal.class" | default "internal" }}
      external: {{ .Values | getOrNil "ingress.external.class" | default "external" }}
      stage: {{ .Values | getOrNil "ingress.stage.class" | default "stage" }}
    zoneMap:
      internal: {{ .Values | getOrNil "ingress.internal.zone" | default "int" }}
      external: {{ .Values | getOrNil "ingress.external.zone" | default "ext" }}
      staging: {{ .Values | getOrNil "ingress.stage.zone" | default "stage" }}
      default: ""
    ingress:
      enabled: true
      tlsEnabled: true
      hosts:
      - secretName: simple-ingress
        config:
          http:
            paths:
            - path: "/"
              backend:
                serviceName: simple-ui
                servicePort: 80
